# coding: utf-8

"""
    ForecastAPI

    Time series forecasting service with multiple algorithms and automatic method selection

    The version of the OpenAPI document: 2.2.0
    Contact: support@forecastapi.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from forecastapi.models.product_insights_request_sales_inner import ProductInsightsRequestSalesInner

class TestProductInsightsRequestSalesInner(unittest.TestCase):
    """ProductInsightsRequestSalesInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProductInsightsRequestSalesInner:
        """Test ProductInsightsRequestSalesInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProductInsightsRequestSalesInner`
        """
        model = ProductInsightsRequestSalesInner()
        if include_optional:
            return ProductInsightsRequestSalesInner(
                var_date = '2024-03-01',
                quantity_sold = 12,
                selling_price = 24.95,
                selling_price_converted = 0,
                currency = '012',
                customer_id = '',
                customer_segment = ''
            )
        else:
            return ProductInsightsRequestSalesInner(
                var_date = '2024-03-01',
                quantity_sold = 12,
                selling_price = 24.95,
        )
        """

    def testProductInsightsRequestSalesInner(self):
        """Test ProductInsightsRequestSalesInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
