# coding: utf-8

"""
    ForecastAPI

    Time series forecasting service with multiple algorithms and automatic method selection

    The version of the OpenAPI document: 2.2.0
    Contact: support@forecastapi.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from forecastapi.models.grouped_forecast_request import GroupedForecastRequest

class TestGroupedForecastRequest(unittest.TestCase):
    """GroupedForecastRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GroupedForecastRequest:
        """Test GroupedForecastRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GroupedForecastRequest`
        """
        model = GroupedForecastRequest()
        if include_optional:
            return GroupedForecastRequest(
                identifier = 'mrr',
                tenant_context = '',
                hierarchy = ["region","plan"],
                reconciliation = 'bottom_up',
                correlation = 0.5,
                frequency = 'M',
                periods = 6,
                data_type = 'sales',
                model = 'standard',
                confidence = 0.1,
                confidence_level = 0.1,
                series = [
                    forecastapi.models.grouped_forecast_series.GroupedForecastSeries(
                        segment = {"region":"eu","plan":"pro"}, 
                        data = [
                            forecastapi.models.grouped_forecast_series_data_inner.GroupedForecastSeries_data_inner(
                                date = 'Mon Jan 01 00:00:00 UTC 2024', 
                                value = 42000, )
                            ], )
                    ]
            )
        else:
            return GroupedForecastRequest(
                identifier = 'mrr',
                hierarchy = ["region","plan"],
                frequency = 'M',
                periods = 6,
                series = [
                    forecastapi.models.grouped_forecast_series.GroupedForecastSeries(
                        segment = {"region":"eu","plan":"pro"}, 
                        data = [
                            forecastapi.models.grouped_forecast_series_data_inner.GroupedForecastSeries_data_inner(
                                date = 'Mon Jan 01 00:00:00 UTC 2024', 
                                value = 42000, )
                            ], )
                    ],
        )
        """

    def testGroupedForecastRequest(self):
        """Test GroupedForecastRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
