# coding: utf-8

"""
    ForecastAPI

    Time series forecasting service with multiple algorithms and automatic method selection

    The version of the OpenAPI document: 2.0.0
    Contact: support@forecastapi.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from forecastapi.models.get_api_root200_response import GetApiRoot200Response

class TestGetApiRoot200Response(unittest.TestCase):
    """GetApiRoot200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetApiRoot200Response:
        """Test GetApiRoot200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetApiRoot200Response`
        """
        model = GetApiRoot200Response()
        if include_optional:
            return GetApiRoot200Response(
                message = 'ok'
            )
        else:
            return GetApiRoot200Response(
        )
        """

    def testGetApiRoot200Response(self):
        """Test GetApiRoot200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
