# coding: utf-8

"""
    ForecastAPI

    Time series forecasting service with multiple algorithms and automatic method selection

    The version of the OpenAPI document: 2.0.0
    Contact: support@forecastapi.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from forecastapi.models.accumulated_forecast_by_period_inner import AccumulatedForecastByPeriodInner

class TestAccumulatedForecastByPeriodInner(unittest.TestCase):
    """AccumulatedForecastByPeriodInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AccumulatedForecastByPeriodInner:
        """Test AccumulatedForecastByPeriodInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AccumulatedForecastByPeriodInner`
        """
        model = AccumulatedForecastByPeriodInner()
        if include_optional:
            return AccumulatedForecastByPeriodInner(
                var_date = 'Mon Apr 01 00:00:00 UTC 2024',
                weight = 0.95,
                cumulative = 328.4,
                cumulative_lower = 301.2,
                cumulative_upper = 355.6
            )
        else:
            return AccumulatedForecastByPeriodInner(
        )
        """

    def testAccumulatedForecastByPeriodInner(self):
        """Test AccumulatedForecastByPeriodInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
