# coding: utf-8

"""
    ForecastAPI

    Time series forecasting service with multiple algorithms and automatic method selection

    The version of the OpenAPI document: 2.0.4
    Contact: support@forecastapi.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from forecastapi.api.forecasting_api import ForecastingApi


class TestForecastingApi(unittest.TestCase):
    """ForecastingApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ForecastingApi()

    def tearDown(self) -> None:
        pass

    def test_create_forecast(self) -> None:
        """Test case for create_forecast

        Generate forecast for time series data
        """
        pass


if __name__ == '__main__':
    unittest.main()
