# coding: utf-8

"""
    ForecastAPI

    Time series forecasting service with multiple algorithms and automatic method selection

    The version of the OpenAPI document: 2.2.0
    Contact: support@forecastapi.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from forecastapi.models.batch_forecast_series_data_inner import BatchForecastSeriesDataInner

class TestBatchForecastSeriesDataInner(unittest.TestCase):
    """BatchForecastSeriesDataInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BatchForecastSeriesDataInner:
        """Test BatchForecastSeriesDataInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BatchForecastSeriesDataInner`
        """
        model = BatchForecastSeriesDataInner()
        if include_optional:
            return BatchForecastSeriesDataInner(
                var_date = 'Mon Jan 01 00:00:00 UTC 2024',
                value = 100
            )
        else:
            return BatchForecastSeriesDataInner(
                var_date = 'Mon Jan 01 00:00:00 UTC 2024',
                value = 100,
        )
        """

    def testBatchForecastSeriesDataInner(self):
        """Test BatchForecastSeriesDataInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
