# coding: utf-8

"""
    ForecastAPI

    Time series forecasting service with multiple algorithms and automatic method selection

    The version of the OpenAPI document: 2.0.0
    Contact: support@forecastapi.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from forecastapi.models.validation_failed_response import ValidationFailedResponse

class TestValidationFailedResponse(unittest.TestCase):
    """ValidationFailedResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ValidationFailedResponse:
        """Test ValidationFailedResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ValidationFailedResponse`
        """
        model = ValidationFailedResponse()
        if include_optional:
            return ValidationFailedResponse(
                error = 'Validation failed',
                errors = {"series.0.data":["The series.0.data field must have at least 2 items."]},
                time_taken_ms = 12.4
            )
        else:
            return ValidationFailedResponse(
        )
        """

    def testValidationFailedResponse(self):
        """Test ValidationFailedResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
