# coding: utf-8

"""
    ForecastAPI

    Time series forecasting service with multiple algorithms and automatic method selection

    The version of the OpenAPI document: 2.0.4
    Contact: support@forecastapi.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from forecastapi.models.product_insights_request import ProductInsightsRequest

class TestProductInsightsRequest(unittest.TestCase):
    """ProductInsightsRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProductInsightsRequest:
        """Test ProductInsightsRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProductInsightsRequest`
        """
        model = ProductInsightsRequest()
        if include_optional:
            return ProductInsightsRequest(
                identifier = 'SKU-12345',
                tenant_context = '',
                product_name = 'Wireless Mouse',
                product_group_id = '',
                base_currency = 'USD',
                baseline_period_days = None,
                locale = 'en',
                sales = [
                    forecastapi.models.product_insights_request_sales_inner.ProductInsightsRequest_sales_inner(
                        date = '2024-03-01', 
                        quantity_sold = 12, 
                        selling_price = 24.95, 
                        selling_price_converted = 0, 
                        currency = '012', 
                        customer_id = '', 
                        customer_segment = '', )
                    ],
                purchases = [
                    forecastapi.models.product_insights_request_purchases_inner.ProductInsightsRequest_purchases_inner(
                        date = '2024-02-20', 
                        quantity_purchased = 100, 
                        cost_price = 10.4, 
                        cost_price_converted = 0, 
                        currency = '012', 
                        supplier_id = '', 
                        purchase_order_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        expected_delivery_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        actual_delivery_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), )
                    ],
                cost_history = [
                    forecastapi.models.product_insights_request_cost_history_inner.ProductInsightsRequest_cost_history_inner(
                        date = '2024-01-01', 
                        cost_price = 9.8, 
                        currency = '012', 
                        change_reason = '', )
                    ],
                insight_settings = forecastapi.models.product_insights_request_insight_settings.ProductInsightsRequest_insight_settings(
                    sales_threshold = 0.05, 
                    margin_threshold = 0.01, 
                    cost_threshold = 0.01, 
                    purchase_threshold = 0.05, 
                    enable_seasonality_detection = True, 
                    severity_levels = [
                        'critical'
                        ], )
            )
        else:
            return ProductInsightsRequest(
                identifier = 'SKU-12345',
        )
        """

    def testProductInsightsRequest(self):
        """Test ProductInsightsRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
