# coding: utf-8

"""
    ForecastAPI

    Time series forecasting service with multiple algorithms and automatic method selection

    The version of the OpenAPI document: 2.0.0
    Contact: support@forecastapi.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from forecastapi.api.anomaly_detection_api import AnomalyDetectionApi


class TestAnomalyDetectionApi(unittest.TestCase):
    """AnomalyDetectionApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AnomalyDetectionApi()

    def tearDown(self) -> None:
        pass

    def test_detect_anomalies(self) -> None:
        """Test case for detect_anomalies

        Detect anomalies in time series data
        """
        pass


if __name__ == '__main__':
    unittest.main()
