# coding: utf-8

"""
    ForecastAPI

    Time series forecasting service with multiple algorithms and automatic method selection

    The version of the OpenAPI document: 2.0.4
    Contact: support@forecastapi.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from forecastapi.models.forecast_response import ForecastResponse

class TestForecastResponse(unittest.TestCase):
    """ForecastResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ForecastResponse:
        """Test ForecastResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ForecastResponse`
        """
        model = ForecastResponse()
        if include_optional:
            return ForecastResponse(
                result = forecastapi.models.forecast_response_result.ForecastResponse_result(
                    identifier = 'SKU-12345', 
                    tenant_context = '', 
                    forecasts = [
                        forecastapi.models.forecast_period.ForecastPeriod(
                            period = 1, 
                            date = 'Mon Apr 01 00:00:00 UTC 2024', 
                            forecast = 168.5, 
                            lower = 162.3, 
                            upper = 174.7, 
                            quantiles = {"0.1":151.2,"0.5":168.5,"0.9":186.0}, )
                        ], 
                    model_info = { }, ),
                adjusted = forecastapi.models.adjusted_forecast.AdjustedForecast(
                    forecasts = [
                        forecastapi.models.forecast_period.ForecastPeriod(
                            period = 1, 
                            date = 'Mon Apr 01 00:00:00 UTC 2024', 
                            forecast = 168.5, 
                            lower = 162.3, 
                            upper = 174.7, 
                            quantiles = {"0.1":151.2,"0.5":168.5,"0.9":186.0}, )
                        ], 
                    adjustments_applied = [
                        forecastapi.models.adjusted_forecast_adjustments_applied_inner.AdjustedForecast_adjustments_applied_inner(
                            type = 'multiplier', 
                            value = 0.8, 
                            from_period = 3, 
                            to_period = 6, 
                            periods_affected = 4, )
                        ], 
                    stored = False, ),
                accumulated = forecastapi.models.accumulated_forecast.AccumulatedForecast(
                    total = 8231.5, 
                    total_reason = '', 
                    lower = 7614.2, 
                    upper = 8848.8, 
                    interval_reason = '', 
                    confidence_level = 0.8, 
                    path = 'baseline', 
                    assumptions = forecastapi.models.accumulated_forecast_assumptions.AccumulatedForecast_assumptions(
                        correlation = 0.5, 
                        correlation_source = 'default', 
                        measured = True, 
                        basis = 'equicorrelated period errors', 
                        decay = 0.95, 
                        discount_rate = 0.1, 
                        periods_per_year = 12, 
                        timing = 'start_of_period', ), 
                    by_period = [
                        forecastapi.models.accumulated_forecast_by_period_inner.AccumulatedForecast_by_period_inner(
                            date = 'Mon Apr 01 00:00:00 UTC 2024', 
                            weight = 0.95, 
                            cumulative = 328.4, 
                            cumulative_lower = 301.2, 
                            cumulative_upper = 355.6, )
                        ], ),
                meta = forecastapi.models.forecast_response_meta.ForecastResponse_meta(
                    selection_metric = 'smape', 
                    timing = forecastapi.models.forecast_response_meta_timing.ForecastResponse_meta_timing(
                        validation = 12.5, 
                        selection = 45.3, 
                        forecasting = 67.8, 
                        total = 125.6, ), )
            )
        else:
            return ForecastResponse(
        )
        """

    def testForecastResponse(self):
        """Test ForecastResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
