# coding: utf-8

"""
    ForecastAPI

    Time series forecasting service with multiple algorithms and automatic method selection

    The version of the OpenAPI document: 2.1.0
    Contact: support@forecastapi.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from forecastapi.api.product_insights_api import ProductInsightsApi


class TestProductInsightsApi(unittest.TestCase):
    """ProductInsightsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ProductInsightsApi()

    def tearDown(self) -> None:
        pass

    def test_create_batch_product_insights(self) -> None:
        """Test case for create_batch_product_insights

        Submit a batch of products for insights analysis
        """
        pass

    def test_create_product_insights(self) -> None:
        """Test case for create_product_insights

        Analyze product performance for anomalies, trends and business insights
        """
        pass

    def test_get_product_insights_batch(self) -> None:
        """Test case for get_product_insights_batch

        Poll a product insights batch for status and results
        """
        pass


if __name__ == '__main__':
    unittest.main()
