# coding: utf-8

"""
    ForecastAPI

    Time series forecasting service with multiple algorithms and automatic method selection

    The version of the OpenAPI document: 2.1.0
    Contact: support@forecastapi.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from forecastapi.models.detect_anomalies500_response import DetectAnomalies500Response

class TestDetectAnomalies500Response(unittest.TestCase):
    """DetectAnomalies500Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DetectAnomalies500Response:
        """Test DetectAnomalies500Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DetectAnomalies500Response`
        """
        model = DetectAnomalies500Response()
        if include_optional:
            return DetectAnomalies500Response(
                error = 'Anomaly detection failed',
                time_taken_ms = 96.5
            )
        else:
            return DetectAnomalies500Response(
        )
        """

    def testDetectAnomalies500Response(self):
        """Test DetectAnomalies500Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
