# coding: utf-8

"""
    ForecastAPI

    Time series forecasting service with multiple algorithms and automatic method selection

    The version of the OpenAPI document: 2.0.4
    Contact: support@forecastapi.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from forecastapi.models.anomaly_detection_response_meta_timing import AnomalyDetectionResponseMetaTiming

class TestAnomalyDetectionResponseMetaTiming(unittest.TestCase):
    """AnomalyDetectionResponseMetaTiming unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AnomalyDetectionResponseMetaTiming:
        """Test AnomalyDetectionResponseMetaTiming
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AnomalyDetectionResponseMetaTiming`
        """
        model = AnomalyDetectionResponseMetaTiming()
        if include_optional:
            return AnomalyDetectionResponseMetaTiming(
                validation = 8.1,
                detection = 42.7,
                total = 50.8
            )
        else:
            return AnomalyDetectionResponseMetaTiming(
        )
        """

    def testAnomalyDetectionResponseMetaTiming(self):
        """Test AnomalyDetectionResponseMetaTiming"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
