# coding: utf-8

"""
    ForecastAPI

    Time series forecasting service with multiple algorithms and automatic method selection

    The version of the OpenAPI document: 2.0.0
    Contact: support@forecastapi.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from forecastapi.models.product_insights_request_insight_settings import ProductInsightsRequestInsightSettings

class TestProductInsightsRequestInsightSettings(unittest.TestCase):
    """ProductInsightsRequestInsightSettings unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProductInsightsRequestInsightSettings:
        """Test ProductInsightsRequestInsightSettings
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProductInsightsRequestInsightSettings`
        """
        model = ProductInsightsRequestInsightSettings()
        if include_optional:
            return ProductInsightsRequestInsightSettings(
                sales_threshold = 0.05,
                margin_threshold = 0.01,
                cost_threshold = 0.01,
                purchase_threshold = 0.05,
                enable_seasonality_detection = True,
                severity_levels = [
                    'critical'
                    ]
            )
        else:
            return ProductInsightsRequestInsightSettings(
        )
        """

    def testProductInsightsRequestInsightSettings(self):
        """Test ProductInsightsRequestInsightSettings"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
