# coding: utf-8

"""
    ForecastAPI

    Time series forecasting service with multiple algorithms and automatic method selection

    The version of the OpenAPI document: 2.1.0
    Contact: support@forecastapi.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from forecastapi.models.value_bounds import ValueBounds

class TestValueBounds(unittest.TestCase):
    """ValueBounds unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ValueBounds:
        """Test ValueBounds
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ValueBounds`
        """
        model = ValueBounds()
        if include_optional:
            return ValueBounds(
                min = 0,
                max = 100
            )
        else:
            return ValueBounds(
        )
        """

    def testValueBounds(self):
        """Test ValueBounds"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
