# coding: utf-8

"""
    ForecastAPI

    Time series forecasting service with multiple algorithms and automatic method selection

    The version of the OpenAPI document: 2.2.0
    Contact: support@forecastapi.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from forecastapi.models.product_insight_recommendation import ProductInsightRecommendation

class TestProductInsightRecommendation(unittest.TestCase):
    """ProductInsightRecommendation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProductInsightRecommendation:
        """Test ProductInsightRecommendation
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProductInsightRecommendation`
        """
        model = ProductInsightRecommendation()
        if include_optional:
            return ProductInsightRecommendation(
                action = 'review_pricing',
                description = '',
                priority = 'high'
            )
        else:
            return ProductInsightRecommendation(
        )
        """

    def testProductInsightRecommendation(self):
        """Test ProductInsightRecommendation"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
