# coding: utf-8

"""
    ForecastAPI

    Time series forecasting service with multiple algorithms and automatic method selection

    The version of the OpenAPI document: 2.0.0
    Contact: support@forecastapi.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from forecastapi.models.anomaly_detection_request_all_of_anomaly_settings import AnomalyDetectionRequestAllOfAnomalySettings

class TestAnomalyDetectionRequestAllOfAnomalySettings(unittest.TestCase):
    """AnomalyDetectionRequestAllOfAnomalySettings unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AnomalyDetectionRequestAllOfAnomalySettings:
        """Test AnomalyDetectionRequestAllOfAnomalySettings
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AnomalyDetectionRequestAllOfAnomalySettings`
        """
        model = AnomalyDetectionRequestAllOfAnomalySettings()
        if include_optional:
            return AnomalyDetectionRequestAllOfAnomalySettings(
                method = 'auto',
                threshold = 0.5,
                multiplier = 0.5,
                seasonal_period = 2,
                minimum_periods = 3
            )
        else:
            return AnomalyDetectionRequestAllOfAnomalySettings(
        )
        """

    def testAnomalyDetectionRequestAllOfAnomalySettings(self):
        """Test AnomalyDetectionRequestAllOfAnomalySettings"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
