# coding: utf-8

"""
    ForecastAPI

    Time series forecasting service with multiple algorithms and automatic method selection

    The version of the OpenAPI document: 2.2.0
    Contact: support@forecastapi.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from forecastapi.models.product_insights_batch_status_response import ProductInsightsBatchStatusResponse

class TestProductInsightsBatchStatusResponse(unittest.TestCase):
    """ProductInsightsBatchStatusResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProductInsightsBatchStatusResponse:
        """Test ProductInsightsBatchStatusResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProductInsightsBatchStatusResponse`
        """
        model = ProductInsightsBatchStatusResponse()
        if include_optional:
            return ProductInsightsBatchStatusResponse(
                identifier = '7f3e2a91-1c4d-4b6a-9e8f-5a6b7c8d9e0f',
                status = 'processing',
                batch_parts = 1,
                results = { },
                parts = [
                    { }
                    ],
                started_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                completed_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return ProductInsightsBatchStatusResponse(
        )
        """

    def testProductInsightsBatchStatusResponse(self):
        """Test ProductInsightsBatchStatusResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
