# coding: utf-8

"""
    ForecastAPI

    Time series forecasting service with multiple algorithms and automatic method selection

    The version of the OpenAPI document: 2.0.4
    Contact: support@forecastapi.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from forecastapi.models.detect_anomalies422_response_one_of import DetectAnomalies422ResponseOneOf

class TestDetectAnomalies422ResponseOneOf(unittest.TestCase):
    """DetectAnomalies422ResponseOneOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DetectAnomalies422ResponseOneOf:
        """Test DetectAnomalies422ResponseOneOf
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DetectAnomalies422ResponseOneOf`
        """
        model = DetectAnomalies422ResponseOneOf()
        if include_optional:
            return DetectAnomalies422ResponseOneOf(
                error = 'Data is not suitable for seasonal method',
                time_taken_ms = 18.3
            )
        else:
            return DetectAnomalies422ResponseOneOf(
        )
        """

    def testDetectAnomalies422ResponseOneOf(self):
        """Test DetectAnomalies422ResponseOneOf"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
