# coding: utf-8

"""
    ForecastAPI

    Time series forecasting service with multiple algorithms and automatic method selection

    The version of the OpenAPI document: 2.0.0
    Contact: support@forecastapi.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from forecastapi.models.get_grouped_forecast404_response import GetGroupedForecast404Response

class TestGetGroupedForecast404Response(unittest.TestCase):
    """GetGroupedForecast404Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetGroupedForecast404Response:
        """Test GetGroupedForecast404Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetGroupedForecast404Response`
        """
        model = GetGroupedForecast404Response()
        if include_optional:
            return GetGroupedForecast404Response(
                message = 'Not found.'
            )
        else:
            return GetGroupedForecast404Response(
        )
        """

    def testGetGroupedForecast404Response(self):
        """Test GetGroupedForecast404Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
