# coding: utf-8

"""
    ForecastAPI

    Time series forecasting service with multiple algorithms and automatic method selection

    The version of the OpenAPI document: 2.1.0
    Contact: support@forecastapi.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from forecastapi.models.traffic_forecasting_response_meta import TrafficForecastingResponseMeta

class TestTrafficForecastingResponseMeta(unittest.TestCase):
    """TrafficForecastingResponseMeta unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TrafficForecastingResponseMeta:
        """Test TrafficForecastingResponseMeta
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TrafficForecastingResponseMeta`
        """
        model = TrafficForecastingResponseMeta()
        if include_optional:
            return TrafficForecastingResponseMeta(
                timing = forecastapi.models.traffic_forecasting_response_meta_timing.TrafficForecastingResponse_meta_timing(
                    validation = 8.5, 
                    forecasting = 145.3, 
                    total = 153.8, )
            )
        else:
            return TrafficForecastingResponseMeta(
        )
        """

    def testTrafficForecastingResponseMeta(self):
        """Test TrafficForecastingResponseMeta"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
