# coding: utf-8

"""
    ForecastAPI

    Time series forecasting service with multiple algorithms and automatic method selection

    The version of the OpenAPI document: 2.1.0
    Contact: support@forecastapi.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from forecastapi.models.batch_forecast_request import BatchForecastRequest

class TestBatchForecastRequest(unittest.TestCase):
    """BatchForecastRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BatchForecastRequest:
        """Test BatchForecastRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BatchForecastRequest`
        """
        model = BatchForecastRequest()
        if include_optional:
            return BatchForecastRequest(
                series = [
                    forecastapi.models.batch_forecast_series.BatchForecastSeries(
                        identifier = 'SKU-001', 
                        tenant_context = 'plan-pro', 
                        data = [
                            forecastapi.models.batch_forecast_series_data_inner.BatchForecastSeries_data_inner(
                                date = 'Mon Jan 01 00:00:00 UTC 2024', 
                                value = 100, )
                            ], 
                        periods = 1, 
                        frequency = 'H', 
                        data_type = '', 
                        confidence = 0.1, 
                        confidence_level = 0.1, 
                        quantiles = [0.1,0.5,0.9], 
                        value_bounds = forecastapi.models.value_bounds.ValueBounds(
                            min = 0, 
                            max = 100, ), 
                        adjustments = [
                            forecastapi.models.adjustments_inner.Adjustments_inner(
                                type = 'multiplier', 
                                value = 0.8, 
                                from_period = 3, 
                                to_period = 9, )
                            ], 
                        accumulate = forecastapi.models.accumulate_options.AccumulateOptions(
                            decay = 0.95, 
                            discount_rate = 0.1, 
                            correlation = 0.5, ), )
                    ],
                file_key = 'batch-uploads/123/2f1f9c2e-6d0f-4a3e-9d55-0c6a70c1a111.json',
                periods = 1,
                frequency = 'M',
                data_type = 'sales',
                model = 'standard',
                confidence = 0.1,
                confidence_level = 0.1,
                quantiles = [0.1,0.5,0.9],
                value_bounds = forecastapi.models.value_bounds.ValueBounds(
                    min = 0, 
                    max = 100, ),
                adjustments = [
                    forecastapi.models.adjustments_inner.Adjustments_inner(
                        type = 'multiplier', 
                        value = 0.8, 
                        from_period = 3, 
                        to_period = 9, )
                    ],
                accumulate = forecastapi.models.accumulate_options.AccumulateOptions(
                    decay = 0.95, 
                    discount_rate = 0.1, 
                    correlation = 0.5, )
            )
        else:
            return BatchForecastRequest(
        )
        """

    def testBatchForecastRequest(self):
        """Test BatchForecastRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
