# coding: utf-8

"""
    ForecastAPI

    Time series forecasting service with multiple algorithms and automatic method selection

    The version of the OpenAPI document: 2.2.0
    Contact: support@forecastapi.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from forecastapi.models.analysis_response import AnalysisResponse

class TestAnalysisResponse(unittest.TestCase):
    """AnalysisResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AnalysisResponse:
        """Test AnalysisResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AnalysisResponse`
        """
        model = AnalysisResponse()
        if include_optional:
            return AnalysisResponse(
                result = forecastapi.models.analysis_response_result.AnalysisResponse_result(
                    pattern_type = 'regular', 
                    characteristics = forecastapi.models.analysis_response_result_characteristics.AnalysisResponse_result_characteristics(
                        total_periods = 24, 
                        non_zero_events = 20, 
                        mean_value = 125.5, 
                        std_deviation = 15.3, 
                        trend_strength = 0.75, 
                        seasonality_detected = True, ), 
                    recommended_methods = ["exponential_smoothing","moving_average"], 
                    confidence = 'high', ),
                meta = forecastapi.models.analysis_response_meta.AnalysisResponse_meta(
                    timing = forecastapi.models.analysis_response_meta_timing.AnalysisResponse_meta_timing(
                        validation = 12.5, 
                        analysing = 85.3, 
                        total = 97.8, ), )
            )
        else:
            return AnalysisResponse(
        )
        """

    def testAnalysisResponse(self):
        """Test AnalysisResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
