# coding: utf-8

"""
    ForecastAPI

    Time series forecasting service with multiple algorithms and automatic method selection

    The version of the OpenAPI document: 2.0.4
    Contact: support@forecastapi.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from forecastapi.models.product_insights_request_cost_history_inner import ProductInsightsRequestCostHistoryInner

class TestProductInsightsRequestCostHistoryInner(unittest.TestCase):
    """ProductInsightsRequestCostHistoryInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProductInsightsRequestCostHistoryInner:
        """Test ProductInsightsRequestCostHistoryInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProductInsightsRequestCostHistoryInner`
        """
        model = ProductInsightsRequestCostHistoryInner()
        if include_optional:
            return ProductInsightsRequestCostHistoryInner(
                var_date = '2024-01-01',
                cost_price = 9.8,
                currency = '012',
                change_reason = ''
            )
        else:
            return ProductInsightsRequestCostHistoryInner(
                var_date = '2024-01-01',
                cost_price = 9.8,
        )
        """

    def testProductInsightsRequestCostHistoryInner(self):
        """Test ProductInsightsRequestCostHistoryInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
