# coding: utf-8

"""
    ForecastAPI

    Time series forecasting service with multiple algorithms and automatic method selection

    The version of the OpenAPI document: 2.0.4
    Contact: support@forecastapi.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from forecastapi.models.grouped_forecast_node import GroupedForecastNode

class TestGroupedForecastNode(unittest.TestCase):
    """GroupedForecastNode unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GroupedForecastNode:
        """Test GroupedForecastNode
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GroupedForecastNode`
        """
        model = GroupedForecastNode()
        if include_optional:
            return GroupedForecastNode(
                identifier = 'mrr',
                segment = {"region":"eu"},
                level = 1,
                is_leaf = False,
                parent = 'total',
                children = ["plan=free|region=eu","plan=pro|region=eu"],
                forecasts = [
                    forecastapi.models.forecast_period.ForecastPeriod(
                        period = 1, 
                        date = 'Mon Apr 01 00:00:00 UTC 2024', 
                        forecast = 168.5, 
                        lower = 162.3, 
                        upper = 174.7, 
                        quantiles = {"0.1":151.2,"0.5":168.5,"0.9":186.0}, )
                    ],
                model_info = { }
            )
        else:
            return GroupedForecastNode(
        )
        """

    def testGroupedForecastNode(self):
        """Test GroupedForecastNode"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
