# coding: utf-8

"""
    ForecastAPI

    Time series forecasting service with multiple algorithms and automatic method selection

    The version of the OpenAPI document: 2.0.4
    Contact: support@forecastapi.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from forecastapi.api.traffic_forecasting_api import TrafficForecastingApi


class TestTrafficForecastingApi(unittest.TestCase):
    """TrafficForecastingApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TrafficForecastingApi()

    def tearDown(self) -> None:
        pass

    def test_create_traffic_forecast(self) -> None:
        """Test case for create_traffic_forecast

        Generate traffic forecasting with infrastructure scaling recommendations
        """
        pass


if __name__ == '__main__':
    unittest.main()
