# coding: utf-8

"""
    ForecastAPI

    Time series forecasting service with multiple algorithms and automatic method selection

    The version of the OpenAPI document: 2.1.0
    Contact: support@forecastapi.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from forecastapi.models.validation_error_response import ValidationErrorResponse

class TestValidationErrorResponse(unittest.TestCase):
    """ValidationErrorResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ValidationErrorResponse:
        """Test ValidationErrorResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ValidationErrorResponse`
        """
        model = ValidationErrorResponse()
        if include_optional:
            return ValidationErrorResponse(
                message = 'Data points exceed the maximum allowed for your current plan (1000).',
                errors = {"data":["Data points exceed the maximum allowed for your current plan (1000)."],"data.0.date":["Invalid date format"],"data.1.value":["Value must be numeric"]}
            )
        else:
            return ValidationErrorResponse(
        )
        """

    def testValidationErrorResponse(self):
        """Test ValidationErrorResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
