# coding: utf-8

"""
    ForecastAPI

    Time series forecasting service with multiple algorithms and automatic method selection

    The version of the OpenAPI document: 2.2.0
    Contact: support@forecastapi.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from forecastapi.models.accumulate_options import AccumulateOptions

class TestAccumulateOptions(unittest.TestCase):
    """AccumulateOptions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AccumulateOptions:
        """Test AccumulateOptions
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AccumulateOptions`
        """
        model = AccumulateOptions()
        if include_optional:
            return AccumulateOptions(
                decay = 0.95,
                discount_rate = 0.1,
                correlation = 0.5
            )
        else:
            return AccumulateOptions(
        )
        """

    def testAccumulateOptions(self):
        """Test AccumulateOptions"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
