# coding: utf-8

"""
    ForecastAPI

    Time series forecasting service with multiple algorithms and automatic method selection

    The version of the OpenAPI document: 2.0.0
    Contact: support@forecastapi.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from forecastapi.models.deprecated_v1404_response import DeprecatedV1404Response

class TestDeprecatedV1404Response(unittest.TestCase):
    """DeprecatedV1404Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DeprecatedV1404Response:
        """Test DeprecatedV1404Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DeprecatedV1404Response`
        """
        model = DeprecatedV1404Response()
        if include_optional:
            return DeprecatedV1404Response(
                error = 'API v1 has been deprecated as of 2025-01'
            )
        else:
            return DeprecatedV1404Response(
        )
        """

    def testDeprecatedV1404Response(self):
        """Test DeprecatedV1404Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
