# coding: utf-8

"""
    ForecastAPI

    Time series forecasting service with multiple algorithms and automatic method selection

    The version of the OpenAPI document: 2.2.0
    Contact: support@forecastapi.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from forecastapi.models.create_product_insights400_response import CreateProductInsights400Response

class TestCreateProductInsights400Response(unittest.TestCase):
    """CreateProductInsights400Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateProductInsights400Response:
        """Test CreateProductInsights400Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateProductInsights400Response`
        """
        model = CreateProductInsights400Response()
        if include_optional:
            return CreateProductInsights400Response(
                error = 'Insufficient data for analysis',
                time_taken_ms = 34.1
            )
        else:
            return CreateProductInsights400Response(
        )
        """

    def testCreateProductInsights400Response(self):
        """Test CreateProductInsights400Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
