# coding: utf-8

"""
    ForecastAPI

    Time series forecasting service with multiple algorithms and automatic method selection

    The version of the OpenAPI document: 2.2.0
    Contact: support@forecastapi.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from forecastapi.models.grouped_forecast_accepted import GroupedForecastAccepted

class TestGroupedForecastAccepted(unittest.TestCase):
    """GroupedForecastAccepted unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GroupedForecastAccepted:
        """Test GroupedForecastAccepted
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GroupedForecastAccepted`
        """
        model = GroupedForecastAccepted()
        if include_optional:
            return GroupedForecastAccepted(
                grouped_forecast_id = 'k3n9x2m4p8q1w5r7',
                status = 'pending',
                series_count = 3,
                node_count = 6,
                reconciliation = 'bottom_up',
                time_taken_ms = 41.2
            )
        else:
            return GroupedForecastAccepted(
        )
        """

    def testGroupedForecastAccepted(self):
        """Test GroupedForecastAccepted"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
