# coding: utf-8

"""
    ForecastAPI

    Time series forecasting service with multiple algorithms and automatic method selection

    The version of the OpenAPI document: 2.2.0
    Contact: support@forecastapi.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from forecastapi.models.create_batch_product_insights422_response import CreateBatchProductInsights422Response

class TestCreateBatchProductInsights422Response(unittest.TestCase):
    """CreateBatchProductInsights422Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateBatchProductInsights422Response:
        """Test CreateBatchProductInsights422Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateBatchProductInsights422Response`
        """
        model = CreateBatchProductInsights422Response()
        if include_optional:
            return CreateBatchProductInsights422Response(
                error = 'Validation failed for 2 series items',
                validation_errors = {
                    'key' : {
                        'key' : [
                            ''
                            ]
                        }
                    },
                valid_count = 98,
                total_count = 100,
                time_taken_ms = 210.4
            )
        else:
            return CreateBatchProductInsights422Response(
        )
        """

    def testCreateBatchProductInsights422Response(self):
        """Test CreateBatchProductInsights422Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
