# coding: utf-8

"""
    ForecastAPI

    Time series forecasting service with multiple algorithms and automatic method selection

    The version of the OpenAPI document: 2.1.0
    Contact: support@forecastapi.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from forecastapi.models.batch_presign_response import BatchPresignResponse

class TestBatchPresignResponse(unittest.TestCase):
    """BatchPresignResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BatchPresignResponse:
        """Test BatchPresignResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BatchPresignResponse`
        """
        model = BatchPresignResponse()
        if include_optional:
            return BatchPresignResponse(
                upload_url = 'https://storage.example.com/batch-uploads/123/2f1f9c2e.json?signature=...',
                headers = {
                    'key' : ''
                    },
                file_key = 'batch-uploads/123/2f1f9c2e-6d0f-4a3e-9d55-0c6a70c1a111.json',
                expires_in = 1800
            )
        else:
            return BatchPresignResponse(
        )
        """

    def testBatchPresignResponse(self):
        """Test BatchPresignResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
