# coding: utf-8

"""
    ForecastAPI

    Time series forecasting service with multiple algorithms and automatic method selection

    The version of the OpenAPI document: 2.2.0
    Contact: support@forecastapi.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from forecastapi.models.batch_forecast_series import BatchForecastSeries

class TestBatchForecastSeries(unittest.TestCase):
    """BatchForecastSeries unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BatchForecastSeries:
        """Test BatchForecastSeries
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BatchForecastSeries`
        """
        model = BatchForecastSeries()
        if include_optional:
            return BatchForecastSeries(
                identifier = 'SKU-001',
                tenant_context = 'plan-pro',
                data = [
                    forecastapi.models.batch_forecast_series_data_inner.BatchForecastSeries_data_inner(
                        date = 'Mon Jan 01 00:00:00 UTC 2024', 
                        value = 100, )
                    ],
                periods = 1,
                frequency = 'H',
                data_type = '',
                confidence = 0.1,
                confidence_level = 0.1,
                model = 'standard',
                quantiles = [0.1,0.5,0.9],
                value_bounds = forecastapi.models.value_bounds.ValueBounds(
                    min = 0, 
                    max = 100, ),
                adjustments = [
                    forecastapi.models.adjustments_inner.Adjustments_inner(
                        type = 'multiplier', 
                        value = 0.8, 
                        from_period = 3, 
                        to_period = 9, )
                    ],
                accumulate = forecastapi.models.accumulate_options.AccumulateOptions(
                    decay = 0.95, 
                    discount_rate = 0.1, 
                    correlation = 0.5, )
            )
        else:
            return BatchForecastSeries(
                identifier = 'SKU-001',
                data = [
                    forecastapi.models.batch_forecast_series_data_inner.BatchForecastSeries_data_inner(
                        date = 'Mon Jan 01 00:00:00 UTC 2024', 
                        value = 100, )
                    ],
        )
        """

    def testBatchForecastSeries(self):
        """Test BatchForecastSeries"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
