# coding: utf-8

"""
    ForecastAPI

    Time series forecasting service with multiple algorithms and automatic method selection

    The version of the OpenAPI document: 2.0.4
    Contact: support@forecastapi.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from forecastapi.models.grouped_forecast_status_response import GroupedForecastStatusResponse

class TestGroupedForecastStatusResponse(unittest.TestCase):
    """GroupedForecastStatusResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GroupedForecastStatusResponse:
        """Test GroupedForecastStatusResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GroupedForecastStatusResponse`
        """
        model = GroupedForecastStatusResponse()
        if include_optional:
            return GroupedForecastStatusResponse(
                grouped_forecast_id = 'k3n9x2m4p8q1w5r7',
                status = 'completed',
                node_count = 6,
                results = forecastapi.models.grouped_forecast_results.GroupedForecastResults(
                    identifier = 'mrr', 
                    tenant_context = '', 
                    hierarchy = ["region","plan"], 
                    reconciliation = forecastapi.models.grouped_forecast_results_reconciliation.GroupedForecastResults_reconciliation(
                        method = 'bottom_up', 
                        correlation = 0.5, 
                        correlation_source = 'default', 
                        measured = False, 
                        variant = 'wls_struct', 
                        nonnegative = True, ), 
                    confidence_level = 0.8, 
                    node_count = 6, 
                    nodes = {
                        'key' : forecastapi.models.grouped_forecast_node.GroupedForecastNode(
                            identifier = 'mrr', 
                            segment = {"region":"eu"}, 
                            level = 1, 
                            is_leaf = False, 
                            parent = 'total', 
                            children = ["plan=free|region=eu","plan=pro|region=eu"], 
                            forecasts = [
                                forecastapi.models.forecast_period.ForecastPeriod(
                                    period = 1, 
                                    date = 'Mon Apr 01 00:00:00 UTC 2024', 
                                    forecast = 168.5, 
                                    lower = 162.3, 
                                    upper = 174.7, 
                                    quantiles = {"0.1":151.2,"0.5":168.5,"0.9":186.0}, )
                                ], 
                            model_info = { }, )
                        }, ),
                error = '',
                started_at = '2026-07-19T09:14:02Z',
                completed_at = '2026-07-19T09:15:31Z',
                created_at = '2026-07-19T09:14:01Z'
            )
        else:
            return GroupedForecastStatusResponse(
        )
        """

    def testGroupedForecastStatusResponse(self):
        """Test GroupedForecastStatusResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
