# coding: utf-8

"""
    ForecastAPI

    Time series forecasting service with multiple algorithms and automatic method selection

    The version of the OpenAPI document: 2.0.0
    Contact: support@forecastapi.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from forecastapi.models.detect_anomalies422_response import DetectAnomalies422Response

class TestDetectAnomalies422Response(unittest.TestCase):
    """DetectAnomalies422Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DetectAnomalies422Response:
        """Test DetectAnomalies422Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DetectAnomalies422Response`
        """
        model = DetectAnomalies422Response()
        if include_optional:
            return DetectAnomalies422Response(
                message = 'Data points exceed the maximum allowed for your current plan (1000).',
                errors = {data=[Data points exceed the maximum allowed for your current plan (1000).], data.0.date=[Invalid date format], data.1.value=[Value must be numeric]},
                error = 'Data is not suitable for seasonal method',
                time_taken_ms = 18.3
            )
        else:
            return DetectAnomalies422Response(
        )
        """

    def testDetectAnomalies422Response(self):
        """Test DetectAnomalies422Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
