# coding: utf-8

"""
    ForecastAPI

    Time series forecasting service with multiple algorithms and automatic method selection

    The version of the OpenAPI document: 2.2.0
    Contact: support@forecastapi.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from forecastapi.models.auto_selection_scores_value import AutoSelectionScoresValue

class TestAutoSelectionScoresValue(unittest.TestCase):
    """AutoSelectionScoresValue unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AutoSelectionScoresValue:
        """Test AutoSelectionScoresValue
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AutoSelectionScoresValue`
        """
        model = AutoSelectionScoresValue()
        if include_optional:
            return AutoSelectionScoresValue(
                mase = 1.337,
                matched_periods = 56,
                forecast_runs = 56
            )
        else:
            return AutoSelectionScoresValue(
        )
        """

    def testAutoSelectionScoresValue(self):
        """Test AutoSelectionScoresValue"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
