# coding: utf-8

"""
    ForecastAPI

    Time series forecasting service with multiple algorithms and automatic method selection

    The version of the OpenAPI document: 2.2.0
    Contact: support@forecastapi.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from forecastapi.models.forecast_period import ForecastPeriod

class TestForecastPeriod(unittest.TestCase):
    """ForecastPeriod unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ForecastPeriod:
        """Test ForecastPeriod
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ForecastPeriod`
        """
        model = ForecastPeriod()
        if include_optional:
            return ForecastPeriod(
                period = 1,
                var_date = 'Mon Apr 01 00:00:00 UTC 2024',
                forecast = 168.5,
                lower = 162.3,
                upper = 174.7,
                quantiles = {"0.1":151.2,"0.5":168.5,"0.9":186.0}
            )
        else:
            return ForecastPeriod(
        )
        """

    def testForecastPeriod(self):
        """Test ForecastPeriod"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
