# coding: utf-8

"""
    ForecastAPI

    Time series forecasting service with multiple algorithms and automatic method selection

    The version of the OpenAPI document: 2.0.4
    Contact: support@forecastapi.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from forecastapi.models.forecast_response_meta_timing import ForecastResponseMetaTiming

class TestForecastResponseMetaTiming(unittest.TestCase):
    """ForecastResponseMetaTiming unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ForecastResponseMetaTiming:
        """Test ForecastResponseMetaTiming
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ForecastResponseMetaTiming`
        """
        model = ForecastResponseMetaTiming()
        if include_optional:
            return ForecastResponseMetaTiming(
                validation = 12.5,
                selection = 45.3,
                forecasting = 67.8,
                total = 125.6
            )
        else:
            return ForecastResponseMetaTiming(
        )
        """

    def testForecastResponseMetaTiming(self):
        """Test ForecastResponseMetaTiming"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
