# coding: utf-8

"""
    ForecastAPI

    Time series forecasting service with multiple algorithms and automatic method selection

    The version of the OpenAPI document: 2.1.0
    Contact: support@forecastapi.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from forecastapi.models.anomaly_detection_request import AnomalyDetectionRequest

class TestAnomalyDetectionRequest(unittest.TestCase):
    """AnomalyDetectionRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AnomalyDetectionRequest:
        """Test AnomalyDetectionRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AnomalyDetectionRequest`
        """
        model = AnomalyDetectionRequest()
        if include_optional:
            return AnomalyDetectionRequest(
                identifier = 'SKU-12345',
                tenant_context = 'plan-pro',
                frequency = 'M',
                start_date = 'Mon Jan 01 00:00:00 UTC 2024',
                data_type = 'sales',
                periods = 6,
                model = 'standard',
                confidence_level = 0.8,
                quantiles = [0.1, 0.5, 0.9],
                value_bounds = forecastapi.models.value_bounds.ValueBounds(
                    min = 0, 
                    max = 100, ),
                adjustments = [
                    forecastapi.models.adjustments_inner.Adjustments_inner(
                        type = 'multiplier', 
                        value = 0.8, 
                        from_period = 3, 
                        to_period = 9, )
                    ],
                accumulate = forecastapi.models.accumulate_options.AccumulateOptions(
                    decay = 0.95, 
                    discount_rate = 0.1, 
                    correlation = 0.5, ),
                selection_metric = 'auto',
                data = [
                    forecastapi.models.forecast_request_data_inner.ForecastRequest_data_inner(
                        date = 'Mon Jan 01 00:00:00 UTC 2024', 
                        value = 150.5, )
                    ],
                anomaly_settings = forecastapi.models.anomaly_detection_request_all_of_anomaly_settings.AnomalyDetectionRequest_allOf_anomaly_settings(
                    method = 'auto', 
                    threshold = 0.5, 
                    multiplier = 0.5, 
                    seasonal_period = 2, 
                    minimum_periods = 3, )
            )
        else:
            return AnomalyDetectionRequest(
                identifier = 'SKU-12345',
                frequency = 'M',
                data_type = 'sales',
                periods = 6,
                data = [
                    forecastapi.models.forecast_request_data_inner.ForecastRequest_data_inner(
                        date = 'Mon Jan 01 00:00:00 UTC 2024', 
                        value = 150.5, )
                    ],
        )
        """

    def testAnomalyDetectionRequest(self):
        """Test AnomalyDetectionRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
