# coding: utf-8

"""
    ForecastAPI

    Time series forecasting service with multiple algorithms and automatic method selection

    The version of the OpenAPI document: 2.0.0
    Contact: support@forecastapi.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from forecastapi.api.analysis_api import AnalysisApi


class TestAnalysisApi(unittest.TestCase):
    """AnalysisApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AnalysisApi()

    def tearDown(self) -> None:
        pass

    def test_analyze_time_series(self) -> None:
        """Test case for analyze_time_series

        Analyze time series data without generating forecast
        """
        pass


if __name__ == '__main__':
    unittest.main()
