# coding: utf-8

"""
    ForecastAPI

    Time series forecasting service with multiple algorithms and automatic method selection

    The version of the OpenAPI document: 2.0.0
    Contact: support@forecastapi.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from forecastapi.models.traffic_forecasting_request_traffic_settings import TrafficForecastingRequestTrafficSettings

class TestTrafficForecastingRequestTrafficSettings(unittest.TestCase):
    """TrafficForecastingRequestTrafficSettings unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TrafficForecastingRequestTrafficSettings:
        """Test TrafficForecastingRequestTrafficSettings
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TrafficForecastingRequestTrafficSettings`
        """
        model = TrafficForecastingRequestTrafficSettings()
        if include_optional:
            return TrafficForecastingRequestTrafficSettings(
                current_capacity = 2000,
                baseline_traffic = 1000,
                scaling_buffer = 0.2,
                scale_up_threshold = 0.8,
                scale_down_threshold = 0.3,
                alert_threshold = 1.5,
                anomaly_threshold = 3.0,
                cost_per_unit = 0.01,
                fixed_cost_per_capacity = 0.1,
                base_scaling_time = 5,
                enable_auto_scaling = False
            )
        else:
            return TrafficForecastingRequestTrafficSettings(
                current_capacity = 2000,
                baseline_traffic = 1000,
        )
        """

    def testTrafficForecastingRequestTrafficSettings(self):
        """Test TrafficForecastingRequestTrafficSettings"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
