# coding: utf-8

"""
    ForecastAPI

    Time series forecasting service with multiple algorithms and automatic method selection

    The version of the OpenAPI document: 2.1.0
    Contact: support@forecastapi.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from forecastapi.models.traffic_forecasting_request_data_inner import TrafficForecastingRequestDataInner

class TestTrafficForecastingRequestDataInner(unittest.TestCase):
    """TrafficForecastingRequestDataInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TrafficForecastingRequestDataInner:
        """Test TrafficForecastingRequestDataInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TrafficForecastingRequestDataInner`
        """
        model = TrafficForecastingRequestDataInner()
        if include_optional:
            return TrafficForecastingRequestDataInner(
                var_date = '2023-12-01 14:00:00',
                value = 1500
            )
        else:
            return TrafficForecastingRequestDataInner(
                var_date = '2023-12-01 14:00:00',
                value = 1500,
        )
        """

    def testTrafficForecastingRequestDataInner(self):
        """Test TrafficForecastingRequestDataInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
