# coding: utf-8

"""
    ForecastAPI

    Time series forecasting service with multiple algorithms and automatic method selection

    The version of the OpenAPI document: 2.0.4
    Contact: support@forecastapi.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from forecastapi.models.product_insights_response import ProductInsightsResponse

class TestProductInsightsResponse(unittest.TestCase):
    """ProductInsightsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProductInsightsResponse:
        """Test ProductInsightsResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProductInsightsResponse`
        """
        model = ProductInsightsResponse()
        if include_optional:
            return ProductInsightsResponse(
                result = forecastapi.models.product_insights_response_result.ProductInsightsResponse_result(
                    identifier = 'SKU-12345', 
                    tenant_context = '', 
                    product_info = forecastapi.models.product_insights_response_result_product_info.ProductInsightsResponse_result_product_info(
                        name = '', 
                        group_id = '', ), 
                    base_currency = 'USD', 
                    insights = [
                        forecastapi.models.product_insight.ProductInsight(
                            class = 'margin', 
                            type = 'margin_compression', 
                            severity = 'warning', 
                            title = 'Margin dropped 8.2% versus baseline', 
                            description = '', 
                            metrics = { }, 
                            recommendation = forecastapi.models.product_insight_recommendation.ProductInsight_recommendation(
                                action = 'review_pricing', 
                                description = '', 
                                priority = 'high', ), 
                            confidence = 'medium', 
                            date = '2024-03-05', 
                            change_status = 'new', )
                        ], 
                    summary = forecastapi.models.product_insights_response_result_summary.ProductInsightsResponse_result_summary(
                        total_insights = 1, 
                        severity_distribution = {"critical":0,"warning":1,"info":0}, 
                        categories = ["profitability"], 
                        analysis_period = forecastapi.models.product_insights_response_result_summary_analysis_period.ProductInsightsResponse_result_summary_analysis_period(
                            start_date = '', 
                            end_date = '', 
                            total_days = 56, ), 
                        data_sources_analyzed = ["sales","purchases","cost_history"], ), 
                    comparison = forecastapi.models.product_insights_response_result_comparison.ProductInsightsResponse_result_comparison(
                        from = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        to = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        result = { }, 
                        developments = forecastapi.models.product_insights_response_result_comparison_developments.ProductInsightsResponse_result_comparison_developments(
                            new = [
                                { }
                                ], 
                            changed = [
                                { }
                                ], 
                            resolved = [
                                { }
                                ], 
                            unchanged_count = 56, ), ), ),
                meta = forecastapi.models.product_insights_response_meta.ProductInsightsResponse_meta(
                    timing = forecastapi.models.product_insights_response_meta_timing.ProductInsightsResponse_meta_timing(
                        validation = 2.1, 
                        analysis = 148.7, 
                        total = 151.9, ), 
                    data_quality = forecastapi.models.product_insights_response_meta_data_quality.ProductInsightsResponse_meta_data_quality(
                        total_data_points = 6, 
                        datasets_provided = ["sales","purchases","cost_history"], ), )
            )
        else:
            return ProductInsightsResponse(
        )
        """

    def testProductInsightsResponse(self):
        """Test ProductInsightsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
