# coding: utf-8

"""
    ForecastAPI

    Time series forecasting service with multiple algorithms and automatic method selection

    The version of the OpenAPI document: 2.0.4
    Contact: support@forecastapi.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from forecastapi.models.create_forecast400_response import CreateForecast400Response

class TestCreateForecast400Response(unittest.TestCase):
    """CreateForecast400Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateForecast400Response:
        """Test CreateForecast400Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateForecast400Response`
        """
        model = CreateForecast400Response()
        if include_optional:
            return CreateForecast400Response(
                error = 'No suitable forecasting method found',
                reason = 'No data available',
                time_taken_ms = 125.5
            )
        else:
            return CreateForecast400Response(
        )
        """

    def testCreateForecast400Response(self):
        """Test CreateForecast400Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
