# coding: utf-8

"""
    ForecastAPI

    Time series forecasting service with multiple algorithms and automatic method selection

    The version of the OpenAPI document: 2.0.4
    Contact: support@forecastapi.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from forecastapi.models.inventory_planning_response import InventoryPlanningResponse

class TestInventoryPlanningResponse(unittest.TestCase):
    """InventoryPlanningResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InventoryPlanningResponse:
        """Test InventoryPlanningResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InventoryPlanningResponse`
        """
        model = InventoryPlanningResponse()
        if include_optional:
            return InventoryPlanningResponse(
                result = forecastapi.models.inventory_planning_response_result.InventoryPlanningResponse_result(
                    identifier = 'SKU-12345', 
                    current_stock = 250, 
                    minimum_stock = 50, 
                    reorder_point = 175.5, 
                    safety_stock = 75.2, 
                    suppliers = [
                        forecastapi.models.inventory_planning_response_result_suppliers_inner.InventoryPlanningResponse_result_suppliers_inner(
                            supplier = 'supplier-a', 
                            order_quantity = 200, 
                            total_cost = 2500.0, 
                            cost_per_unit = 12.5, 
                            expected_delivery = 'Mon Jan 15 00:00:00 UTC 2024', 
                            lead_time_days = 14, 
                            minimum_order_quantity = 100, 
                            reliability_score = 0.98, 
                            lead_time_demand = 87.5, 
                            safety_stock = 75.2, 
                            reorder_point = 175.5, 
                            reason = '$12.50 per unit, fast delivery, high reliability', )
                        ], 
                    stock_analysis = forecastapi.models.inventory_planning_response_result_stock_analysis.InventoryPlanningResponse_result_stock_analysis(
                        days_of_coverage = 45, 
                        stockout_risk = 0.15, 
                        next_order_date = 'Sat Jan 20 00:00:00 UTC 2024', 
                        daily_demand_rate = 5.5, 
                        stock_status = 'adequate', ), 
                    forecast_data = [
                        forecastapi.models.inventory_planning_response_result_forecast_data_inner.InventoryPlanningResponse_result_forecast_data_inner(
                            period = 1, 
                            date = 'Mon Jan 01 00:00:00 UTC 2024', 
                            forecast = 165.75, 
                            lower = 145.25, 
                            upper = 186.25, )
                        ], ),
                meta = forecastapi.models.inventory_planning_response_meta.InventoryPlanningResponse_meta(
                    timing = forecastapi.models.inventory_planning_response_meta_timing.InventoryPlanningResponse_meta_timing(
                        validation = 12.5, 
                        planning = 187.3, 
                        total = 199.8, ), )
            )
        else:
            return InventoryPlanningResponse(
        )
        """

    def testInventoryPlanningResponse(self):
        """Test InventoryPlanningResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
