# coding: utf-8

"""
    ForecastAPI

    Time series forecasting service with multiple algorithms and automatic method selection

    The version of the OpenAPI document: 2.1.0
    Contact: support@forecastapi.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from forecastapi.models.inventory_planning_request import InventoryPlanningRequest

class TestInventoryPlanningRequest(unittest.TestCase):
    """InventoryPlanningRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InventoryPlanningRequest:
        """Test InventoryPlanningRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InventoryPlanningRequest`
        """
        model = InventoryPlanningRequest()
        if include_optional:
            return InventoryPlanningRequest(
                identifier = 'SKU-12345',
                frequency = 'M',
                start_date = 'Mon Jan 01 00:00:00 UTC 2024',
                periods = 6,
                enable_intelligent_aggregation = True,
                confidence_level = 0.95,
                data = [
                    forecastapi.models.inventory_planning_request_data_inner.InventoryPlanningRequest_data_inner(
                        date = 'Sun Jan 01 00:00:00 UTC 2023', 
                        value = 150.5, )
                    ],
                inventory_settings = forecastapi.models.inventory_planning_request_inventory_settings.InventoryPlanningRequest_inventory_settings(
                    current_stock = 250, 
                    minimum_stock = 50, 
                    service_level = 0.95, 
                    suppliers = [
                        forecastapi.models.inventory_planning_request_inventory_settings_suppliers_inner.InventoryPlanningRequest_inventory_settings_suppliers_inner(
                            identifier = 'supplier-a', 
                            lead_time_days = 14, 
                            minimum_order_quantity = 100, 
                            cost_per_unit = 12.5, 
                            reliability_score = 0.98, )
                        ], )
            )
        else:
            return InventoryPlanningRequest(
                identifier = 'SKU-12345',
                frequency = 'M',
                periods = 6,
                data = [
                    forecastapi.models.inventory_planning_request_data_inner.InventoryPlanningRequest_data_inner(
                        date = 'Sun Jan 01 00:00:00 UTC 2023', 
                        value = 150.5, )
                    ],
                inventory_settings = forecastapi.models.inventory_planning_request_inventory_settings.InventoryPlanningRequest_inventory_settings(
                    current_stock = 250, 
                    minimum_stock = 50, 
                    service_level = 0.95, 
                    suppliers = [
                        forecastapi.models.inventory_planning_request_inventory_settings_suppliers_inner.InventoryPlanningRequest_inventory_settings_suppliers_inner(
                            identifier = 'supplier-a', 
                            lead_time_days = 14, 
                            minimum_order_quantity = 100, 
                            cost_per_unit = 12.5, 
                            reliability_score = 0.98, )
                        ], ),
        )
        """

    def testInventoryPlanningRequest(self):
        """Test InventoryPlanningRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
