# coding: utf-8

"""
    ForecastAPI

    Time series forecasting service with multiple algorithms and automatic method selection

    The version of the OpenAPI document: 2.1.0
    Contact: support@forecastapi.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from forecastapi.models.create_batch_product_insights500_response import CreateBatchProductInsights500Response

class TestCreateBatchProductInsights500Response(unittest.TestCase):
    """CreateBatchProductInsights500Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateBatchProductInsights500Response:
        """Test CreateBatchProductInsights500Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateBatchProductInsights500Response`
        """
        model = CreateBatchProductInsights500Response()
        if include_optional:
            return CreateBatchProductInsights500Response(
                error = 'Product insights analysis failed',
                time_taken_ms = 96.5
            )
        else:
            return CreateBatchProductInsights500Response(
        )
        """

    def testCreateBatchProductInsights500Response(self):
        """Test CreateBatchProductInsights500Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
