# coding: utf-8

"""
    ForecastAPI

    Time series forecasting service with multiple algorithms and automatic method selection

    The version of the OpenAPI document: 2.1.0
    Contact: support@forecastapi.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from forecastapi.models.create_forecast502_response import CreateForecast502Response

class TestCreateForecast502Response(unittest.TestCase):
    """CreateForecast502Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateForecast502Response:
        """Test CreateForecast502Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateForecast502Response`
        """
        model = CreateForecast502Response()
        if include_optional:
            return CreateForecast502Response(
                error = 'Forecasting service error',
                time_taken_ms = 5120.4
            )
        else:
            return CreateForecast502Response(
        )
        """

    def testCreateForecast502Response(self):
        """Test CreateForecast502Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
