# coding: utf-8

"""
    ForecastAPI

    Time series forecasting service with multiple algorithms and automatic method selection

    The version of the OpenAPI document: 2.0.4
    Contact: support@forecastapi.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from forecastapi.models.product_insights_response_meta_timing import ProductInsightsResponseMetaTiming

class TestProductInsightsResponseMetaTiming(unittest.TestCase):
    """ProductInsightsResponseMetaTiming unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProductInsightsResponseMetaTiming:
        """Test ProductInsightsResponseMetaTiming
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProductInsightsResponseMetaTiming`
        """
        model = ProductInsightsResponseMetaTiming()
        if include_optional:
            return ProductInsightsResponseMetaTiming(
                validation = 2.1,
                analysis = 148.7,
                total = 151.9
            )
        else:
            return ProductInsightsResponseMetaTiming(
        )
        """

    def testProductInsightsResponseMetaTiming(self):
        """Test ProductInsightsResponseMetaTiming"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
