# coding: utf-8

"""
    ForecastAPI

    Time series forecasting service with multiple algorithms and automatic method selection

    The version of the OpenAPI document: 2.2.0
    Contact: support@forecastapi.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from forecastapi.api.grouped_forecasting_api import GroupedForecastingApi


class TestGroupedForecastingApi(unittest.TestCase):
    """GroupedForecastingApi unit test stubs"""

    def setUp(self) -> None:
        self.api = GroupedForecastingApi()

    def tearDown(self) -> None:
        pass

    def test_create_grouped_forecast(self) -> None:
        """Test case for create_grouped_forecast

        Submit a grouped (hierarchical) forecast with reconciliation
        """
        pass

    def test_get_grouped_forecast(self) -> None:
        """Test case for get_grouped_forecast

        Poll a grouped forecast for status and results
        """
        pass


if __name__ == '__main__':
    unittest.main()
