# coding: utf-8

"""
    ForecastAPI

    Time series forecasting service with multiple algorithms and automatic method selection

    The version of the OpenAPI document: 2.2.0
    Contact: support@forecastapi.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from forecastapi.models.auto_selection import AutoSelection

class TestAutoSelection(unittest.TestCase):
    """AutoSelection unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AutoSelection:
        """Test AutoSelection
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AutoSelection`
        """
        model = AutoSelection()
        if include_optional:
            return AutoSelection(
                requested = 'auto',
                selected = 'ensemble',
                reason = 'no_history',
                scores = {
                    'key' : forecastapi.models.auto_selection_scores_value.AutoSelection_scores_value(
                        mase = 1.337, 
                        matched_periods = 56, 
                        forecast_runs = 56, )
                    }
            )
        else:
            return AutoSelection(
        )
        """

    def testAutoSelection(self):
        """Test AutoSelection"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
