# coding: utf-8

"""
    ForecastAPI

    Time series forecasting service with multiple algorithms and automatic method selection

    The version of the OpenAPI document: 2.0.0
    Contact: support@forecastapi.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from forecastapi.models.product_insights_request_purchases_inner import ProductInsightsRequestPurchasesInner

class TestProductInsightsRequestPurchasesInner(unittest.TestCase):
    """ProductInsightsRequestPurchasesInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProductInsightsRequestPurchasesInner:
        """Test ProductInsightsRequestPurchasesInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProductInsightsRequestPurchasesInner`
        """
        model = ProductInsightsRequestPurchasesInner()
        if include_optional:
            return ProductInsightsRequestPurchasesInner(
                var_date = '2024-02-20',
                quantity_purchased = 100,
                cost_price = 10.4,
                cost_price_converted = 0,
                currency = '012',
                supplier_id = '',
                purchase_order_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                expected_delivery_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                actual_delivery_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date()
            )
        else:
            return ProductInsightsRequestPurchasesInner(
                var_date = '2024-02-20',
                quantity_purchased = 100,
                cost_price = 10.4,
        )
        """

    def testProductInsightsRequestPurchasesInner(self):
        """Test ProductInsightsRequestPurchasesInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
