# coding: utf-8

"""
    ForecastAPI

    Time series forecasting service with multiple algorithms and automatic method selection

    The version of the OpenAPI document: 2.2.0
    Contact: support@forecastapi.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from forecastapi.models.adjustments_inner import AdjustmentsInner

class TestAdjustmentsInner(unittest.TestCase):
    """AdjustmentsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AdjustmentsInner:
        """Test AdjustmentsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AdjustmentsInner`
        """
        model = AdjustmentsInner()
        if include_optional:
            return AdjustmentsInner(
                type = 'multiplier',
                value = 0.8,
                from_period = 3,
                to_period = 9
            )
        else:
            return AdjustmentsInner(
                type = 'multiplier',
                value = 0.8,
        )
        """

    def testAdjustmentsInner(self):
        """Test AdjustmentsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
