# coding: utf-8

"""
    ForecastAPI

    Time series forecasting service with multiple algorithms and automatic method selection

    The version of the OpenAPI document: 2.2.0
    Contact: support@forecastapi.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from forecastapi.models.batch_forecast_status_response import BatchForecastStatusResponse

class TestBatchForecastStatusResponse(unittest.TestCase):
    """BatchForecastStatusResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BatchForecastStatusResponse:
        """Test BatchForecastStatusResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BatchForecastStatusResponse`
        """
        model = BatchForecastStatusResponse()
        if include_optional:
            return BatchForecastStatusResponse(
                identifier = '9d2c1b34-5e6f-4a7b-8c9d-0e1f2a3b4c5d',
                status = 'completed',
                batch_parts = 1,
                results = forecastapi.models.batch_forecast_status_response_results.BatchForecastStatusResponse_results(
                    summary = forecastapi.models.batch_forecast_status_response_results_summary.BatchForecastStatusResponse_results_summary(
                        total_series = 250, 
                        completed = 248, 
                        failed = 2, 
                        model_distribution = {"standard":250}, 
                        total_processing_time_ms = 512340.0, 
                        avg_processing_time_ms = 2049.4, 
                        error = '', ), 
                    data = {
                        'key' : {"identifier":"SKU-001","tenant_context":null,"forecasts":[{"period":1,"date":"2024-04-01","forecast":168.5,"lower":162.3,"upper":174.7}]}
                        }, ),
                parts = [
                    forecastapi.models.batch_forecast_status_response_parts_inner.BatchForecastStatusResponse_parts_inner(
                        status = 'pending', 
                        started_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        completed_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
                started_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                completed_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return BatchForecastStatusResponse(
        )
        """

    def testBatchForecastStatusResponse(self):
        """Test BatchForecastStatusResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
