# coding: utf-8

"""
    ForecastAPI

    Time series forecasting service with multiple algorithms and automatic method selection

    The version of the OpenAPI document: 2.0.0
    Contact: support@forecastapi.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from forecastapi.models.adjusted_forecast import AdjustedForecast

class TestAdjustedForecast(unittest.TestCase):
    """AdjustedForecast unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AdjustedForecast:
        """Test AdjustedForecast
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AdjustedForecast`
        """
        model = AdjustedForecast()
        if include_optional:
            return AdjustedForecast(
                forecasts = [
                    forecastapi.models.forecast_period.ForecastPeriod(
                        period = 1, 
                        date = 'Mon Apr 01 00:00:00 UTC 2024', 
                        forecast = 168.5, 
                        lower = 162.3, 
                        upper = 174.7, 
                        quantiles = {"0.1":151.2,"0.5":168.5,"0.9":186.0}, )
                    ],
                adjustments_applied = [
                    forecastapi.models.adjusted_forecast_adjustments_applied_inner.AdjustedForecast_adjustments_applied_inner(
                        type = 'multiplier', 
                        value = 0.8, 
                        from_period = 3, 
                        to_period = 6, 
                        periods_affected = 4, )
                    ],
                stored = False
            )
        else:
            return AdjustedForecast(
        )
        """

    def testAdjustedForecast(self):
        """Test AdjustedForecast"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
