# coding: utf-8

"""
    ForecastAPI

    Time series forecasting service with multiple algorithms and automatic method selection

    The version of the OpenAPI document: 2.1.0
    Contact: support@forecastapi.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from forecastapi.models.inventory_planning_response_meta_timing import InventoryPlanningResponseMetaTiming

class TestInventoryPlanningResponseMetaTiming(unittest.TestCase):
    """InventoryPlanningResponseMetaTiming unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InventoryPlanningResponseMetaTiming:
        """Test InventoryPlanningResponseMetaTiming
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InventoryPlanningResponseMetaTiming`
        """
        model = InventoryPlanningResponseMetaTiming()
        if include_optional:
            return InventoryPlanningResponseMetaTiming(
                validation = 12.5,
                planning = 187.3,
                total = 199.8
            )
        else:
            return InventoryPlanningResponseMetaTiming(
        )
        """

    def testInventoryPlanningResponseMetaTiming(self):
        """Test InventoryPlanningResponseMetaTiming"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
