# coding: utf-8

"""
    ForecastAPI

    Time series forecasting service with multiple algorithms and automatic method selection

    The version of the OpenAPI document: 2.0.0
    Contact: support@forecastapi.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from forecastapi.models.create_inventory_plan400_response import CreateInventoryPlan400Response

class TestCreateInventoryPlan400Response(unittest.TestCase):
    """CreateInventoryPlan400Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateInventoryPlan400Response:
        """Test CreateInventoryPlan400Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateInventoryPlan400Response`
        """
        model = CreateInventoryPlan400Response()
        if include_optional:
            return CreateInventoryPlan400Response(
                error = 'No suitable forecasting method found',
                reason = 'Insufficient historical data for reliable forecasting',
                time_taken_ms = 125.5
            )
        else:
            return CreateInventoryPlan400Response(
        )
        """

    def testCreateInventoryPlan400Response(self):
        """Test CreateInventoryPlan400Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
