# coding: utf-8

"""
    ForecastAPI

    Time series forecasting service with multiple algorithms and automatic method selection

    The version of the OpenAPI document: 2.2.0
    Contact: support@forecastapi.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from forecastapi.models.forecast_request_data_inner import ForecastRequestDataInner

class TestForecastRequestDataInner(unittest.TestCase):
    """ForecastRequestDataInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ForecastRequestDataInner:
        """Test ForecastRequestDataInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ForecastRequestDataInner`
        """
        model = ForecastRequestDataInner()
        if include_optional:
            return ForecastRequestDataInner(
                var_date = 'Mon Jan 01 00:00:00 UTC 2024',
                value = 150.5
            )
        else:
            return ForecastRequestDataInner(
                var_date = 'Mon Jan 01 00:00:00 UTC 2024',
                value = 150.5,
        )
        """

    def testForecastRequestDataInner(self):
        """Test ForecastRequestDataInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
