# coding: utf-8

"""
    ForecastAPI

    Time series forecasting service with multiple algorithms and automatic method selection

    The version of the OpenAPI document: 2.0.0
    Contact: support@forecastapi.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from forecastapi.models.adjusted_forecast_adjustments_applied_inner import AdjustedForecastAdjustmentsAppliedInner

class TestAdjustedForecastAdjustmentsAppliedInner(unittest.TestCase):
    """AdjustedForecastAdjustmentsAppliedInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AdjustedForecastAdjustmentsAppliedInner:
        """Test AdjustedForecastAdjustmentsAppliedInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AdjustedForecastAdjustmentsAppliedInner`
        """
        model = AdjustedForecastAdjustmentsAppliedInner()
        if include_optional:
            return AdjustedForecastAdjustmentsAppliedInner(
                type = 'multiplier',
                value = 0.8,
                from_period = 3,
                to_period = 6,
                periods_affected = 4
            )
        else:
            return AdjustedForecastAdjustmentsAppliedInner(
        )
        """

    def testAdjustedForecastAdjustmentsAppliedInner(self):
        """Test AdjustedForecastAdjustmentsAppliedInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
