# coding: utf-8

"""
    ForecastAPI

    Time series forecasting service with multiple algorithms and automatic method selection

    The version of the OpenAPI document: 2.1.0
    Contact: support@forecastapi.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from forecastapi.models.grouped_forecast_series import GroupedForecastSeries

class TestGroupedForecastSeries(unittest.TestCase):
    """GroupedForecastSeries unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GroupedForecastSeries:
        """Test GroupedForecastSeries
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GroupedForecastSeries`
        """
        model = GroupedForecastSeries()
        if include_optional:
            return GroupedForecastSeries(
                segment = {"region":"eu","plan":"pro"},
                data = [
                    forecastapi.models.grouped_forecast_series_data_inner.GroupedForecastSeries_data_inner(
                        date = 'Mon Jan 01 00:00:00 UTC 2024', 
                        value = 42000, )
                    ]
            )
        else:
            return GroupedForecastSeries(
                segment = {"region":"eu","plan":"pro"},
                data = [
                    forecastapi.models.grouped_forecast_series_data_inner.GroupedForecastSeries_data_inner(
                        date = 'Mon Jan 01 00:00:00 UTC 2024', 
                        value = 42000, )
                    ],
        )
        """

    def testGroupedForecastSeries(self):
        """Test GroupedForecastSeries"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
