# coding: utf-8

"""
    ForecastAPI

    Time series forecasting service with multiple algorithms and automatic method selection

    The version of the OpenAPI document: 2.1.0
    Contact: support@forecastapi.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from forecastapi.models.create_inventory_plan500_response import CreateInventoryPlan500Response

class TestCreateInventoryPlan500Response(unittest.TestCase):
    """CreateInventoryPlan500Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateInventoryPlan500Response:
        """Test CreateInventoryPlan500Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateInventoryPlan500Response`
        """
        model = CreateInventoryPlan500Response()
        if include_optional:
            return CreateInventoryPlan500Response(
                error = 'Inventory planning failed',
                time_taken_ms = 256.8
            )
        else:
            return CreateInventoryPlan500Response(
        )
        """

    def testCreateInventoryPlan500Response(self):
        """Test CreateInventoryPlan500Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
