# coding: utf-8

"""
    ForecastAPI

    Time series forecasting service with multiple algorithms and automatic method selection

    The version of the OpenAPI document: 2.2.0
    Contact: support@forecastapi.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from forecastapi.models.accumulated_forecast import AccumulatedForecast

class TestAccumulatedForecast(unittest.TestCase):
    """AccumulatedForecast unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AccumulatedForecast:
        """Test AccumulatedForecast
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AccumulatedForecast`
        """
        model = AccumulatedForecast()
        if include_optional:
            return AccumulatedForecast(
                total = 8231.5,
                total_reason = '',
                lower = 7614.2,
                upper = 8848.8,
                interval_reason = '',
                confidence_level = 0.8,
                path = 'baseline',
                assumptions = forecastapi.models.accumulated_forecast_assumptions.AccumulatedForecast_assumptions(
                    correlation = 0.5, 
                    correlation_source = 'default', 
                    measured = True, 
                    basis = 'equicorrelated period errors', 
                    decay = 0.95, 
                    discount_rate = 0.1, 
                    periods_per_year = 12, 
                    timing = 'start_of_period', ),
                by_period = [
                    forecastapi.models.accumulated_forecast_by_period_inner.AccumulatedForecast_by_period_inner(
                        date = 'Mon Apr 01 00:00:00 UTC 2024', 
                        weight = 0.95, 
                        cumulative = 328.4, 
                        cumulative_lower = 301.2, 
                        cumulative_upper = 355.6, )
                    ]
            )
        else:
            return AccumulatedForecast(
        )
        """

    def testAccumulatedForecast(self):
        """Test AccumulatedForecast"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
