# coding: utf-8

"""
    ForecastAPI

    Time series forecasting service with multiple algorithms and automatic method selection

    The version of the OpenAPI document: 2.0.0
    Contact: support@forecastapi.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from forecastapi.api.batch_forecasting_api import BatchForecastingApi


class TestBatchForecastingApi(unittest.TestCase):
    """BatchForecastingApi unit test stubs"""

    def setUp(self) -> None:
        self.api = BatchForecastingApi()

    def tearDown(self) -> None:
        pass

    def test_create_batch_forecast(self) -> None:
        """Test case for create_batch_forecast

        Submit a batch of series for forecasting
        """
        pass

    def test_get_batch_forecast(self) -> None:
        """Test case for get_batch_forecast

        Poll a batch forecast for status and results
        """
        pass

    def test_presign_batch_forecast(self) -> None:
        """Test case for presign_batch_forecast

        Get a presigned URL for a file-based batch upload
        """
        pass


if __name__ == '__main__':
    unittest.main()
