# coding: utf-8

"""
    ForecastAPI

    Time series forecasting service with multiple algorithms and automatic method selection

    The version of the OpenAPI document: 2.0.0
    Contact: support@forecastapi.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from forecastapi.models.batch_forecast_accepted import BatchForecastAccepted

class TestBatchForecastAccepted(unittest.TestCase):
    """BatchForecastAccepted unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BatchForecastAccepted:
        """Test BatchForecastAccepted
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BatchForecastAccepted`
        """
        model = BatchForecastAccepted()
        if include_optional:
            return BatchForecastAccepted(
                batch_id = '9d2c1b34-5e6f-4a7b-8c9d-0e1f2a3b4c5d',
                status = 'pending',
                series_count = 250,
                time_taken_ms = 84.2
            )
        else:
            return BatchForecastAccepted(
        )
        """

    def testBatchForecastAccepted(self):
        """Test BatchForecastAccepted"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
