# coding: utf-8

"""
    ForecastAPI

    Time series forecasting service with multiple algorithms and automatic method selection

    The version of the OpenAPI document: 2.0.4
    Contact: support@forecastapi.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from forecastapi.models.inventory_planning_request_inventory_settings_suppliers_inner import InventoryPlanningRequestInventorySettingsSuppliersInner

class TestInventoryPlanningRequestInventorySettingsSuppliersInner(unittest.TestCase):
    """InventoryPlanningRequestInventorySettingsSuppliersInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InventoryPlanningRequestInventorySettingsSuppliersInner:
        """Test InventoryPlanningRequestInventorySettingsSuppliersInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InventoryPlanningRequestInventorySettingsSuppliersInner`
        """
        model = InventoryPlanningRequestInventorySettingsSuppliersInner()
        if include_optional:
            return InventoryPlanningRequestInventorySettingsSuppliersInner(
                identifier = 'supplier-a',
                lead_time_days = 14,
                minimum_order_quantity = 100,
                cost_per_unit = 12.5,
                reliability_score = 0.98
            )
        else:
            return InventoryPlanningRequestInventorySettingsSuppliersInner(
                identifier = 'supplier-a',
                lead_time_days = 14,
                minimum_order_quantity = 100,
                cost_per_unit = 12.5,
        )
        """

    def testInventoryPlanningRequestInventorySettingsSuppliersInner(self):
        """Test InventoryPlanningRequestInventorySettingsSuppliersInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
