# coding: utf-8

"""
    ForecastAPI

    Time series forecasting service with multiple algorithms and automatic method selection

    The version of the OpenAPI document: 2.2.0
    Contact: support@forecastapi.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from forecastapi.models.product_insight import ProductInsight

class TestProductInsight(unittest.TestCase):
    """ProductInsight unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProductInsight:
        """Test ProductInsight
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProductInsight`
        """
        model = ProductInsight()
        if include_optional:
            return ProductInsight(
                var_class = 'margin',
                type = 'margin_compression',
                severity = 'warning',
                title = 'Margin dropped 8.2% versus baseline',
                description = '',
                metrics = { },
                recommendation = forecastapi.models.product_insight_recommendation.ProductInsight_recommendation(
                    action = 'review_pricing', 
                    description = '', 
                    priority = 'high', ),
                confidence = 'medium',
                var_date = '2024-03-05',
                change_status = 'new'
            )
        else:
            return ProductInsight(
        )
        """

    def testProductInsight(self):
        """Test ProductInsight"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
