# coding: utf-8

"""
    ForecastAPI

    Time series forecasting service with multiple algorithms and automatic method selection

    The version of the OpenAPI document: 2.0.0
    Contact: support@forecastapi.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from forecastapi.models.product_insights_response_meta import ProductInsightsResponseMeta

class TestProductInsightsResponseMeta(unittest.TestCase):
    """ProductInsightsResponseMeta unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProductInsightsResponseMeta:
        """Test ProductInsightsResponseMeta
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProductInsightsResponseMeta`
        """
        model = ProductInsightsResponseMeta()
        if include_optional:
            return ProductInsightsResponseMeta(
                timing = forecastapi.models.product_insights_response_meta_timing.ProductInsightsResponse_meta_timing(
                    validation = 2.1, 
                    analysis = 148.7, 
                    total = 151.9, ),
                data_quality = forecastapi.models.product_insights_response_meta_data_quality.ProductInsightsResponse_meta_data_quality(
                    total_data_points = 6, 
                    datasets_provided = ["sales","purchases","cost_history"], )
            )
        else:
            return ProductInsightsResponseMeta(
        )
        """

    def testProductInsightsResponseMeta(self):
        """Test ProductInsightsResponseMeta"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
