# coding: utf-8

"""
    ForecastAPI

    Time series forecasting service with multiple algorithms and automatic method selection

    The version of the OpenAPI document: 2.0.0
    Contact: support@forecastapi.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from forecastapi.models.analysis_response_meta import AnalysisResponseMeta

class TestAnalysisResponseMeta(unittest.TestCase):
    """AnalysisResponseMeta unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AnalysisResponseMeta:
        """Test AnalysisResponseMeta
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AnalysisResponseMeta`
        """
        model = AnalysisResponseMeta()
        if include_optional:
            return AnalysisResponseMeta(
                timing = forecastapi.models.analysis_response_meta_timing.AnalysisResponse_meta_timing(
                    validation = 12.5, 
                    analysing = 85.3, 
                    total = 97.8, )
            )
        else:
            return AnalysisResponseMeta(
        )
        """

    def testAnalysisResponseMeta(self):
        """Test AnalysisResponseMeta"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
