# coding: utf-8

"""
    ForecastAPI

    Time series forecasting service with multiple algorithms and automatic method selection

    The version of the OpenAPI document: 2.0.3
    Contact: support@forecastapi.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import warnings
from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from pydantic import Field, StrictStr
from typing_extensions import Annotated
from forecastapi.models.grouped_forecast_accepted import GroupedForecastAccepted
from forecastapi.models.grouped_forecast_request import GroupedForecastRequest
from forecastapi.models.grouped_forecast_status_response import GroupedForecastStatusResponse

from forecastapi.api_client import ApiClient, RequestSerialized
from forecastapi.api_response import ApiResponse
from forecastapi.rest import RESTResponseType


class GroupedForecastingApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @validate_call
    def create_grouped_forecast(
        self,
        grouped_forecast_request: GroupedForecastRequest,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> GroupedForecastAccepted:
        """Submit a grouped (hierarchical) forecast with reconciliation

        Forecast a set of related series that roll up to a total — MRR by plan and region, demand by warehouse, revenue by category — and get back one coherent result: every parent equals the sum of its children, in every period, at every level.  You send only the **leaves** of the hierarchy (every combination of the declared dimensions, each with its own history). The API derives every aggregate level and the grand total by summing the leaf histories, forecasts the nodes, reconciles them to coherence, and stores each node as its own entity with independently tracked accuracy.  Processing is **asynchronous**: submission returns `202` with an id to poll via `GET /v2/forecast/grouped/{grouped_forecast_id}`. The run executes in the background as one all-or-nothing job — a hierarchy is one coherent answer, so there is no partial success. If any node cannot be forecast, the run fails with the reason rather than returning numbers that don't add up.  If you just want independent forecasts per slice — no coherent roll-up — the batch endpoint with per-series identifiers or `tenant_context` is simpler and tolerates per-series failure. 

        :param grouped_forecast_request: (required)
        :type grouped_forecast_request: GroupedForecastRequest
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._create_grouped_forecast_serialize(
            grouped_forecast_request=grouped_forecast_request,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '202': "GroupedForecastAccepted",
            '401': "ErrorResponse",
            '422': "ValidationFailedResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def create_grouped_forecast_with_http_info(
        self,
        grouped_forecast_request: GroupedForecastRequest,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[GroupedForecastAccepted]:
        """Submit a grouped (hierarchical) forecast with reconciliation

        Forecast a set of related series that roll up to a total — MRR by plan and region, demand by warehouse, revenue by category — and get back one coherent result: every parent equals the sum of its children, in every period, at every level.  You send only the **leaves** of the hierarchy (every combination of the declared dimensions, each with its own history). The API derives every aggregate level and the grand total by summing the leaf histories, forecasts the nodes, reconciles them to coherence, and stores each node as its own entity with independently tracked accuracy.  Processing is **asynchronous**: submission returns `202` with an id to poll via `GET /v2/forecast/grouped/{grouped_forecast_id}`. The run executes in the background as one all-or-nothing job — a hierarchy is one coherent answer, so there is no partial success. If any node cannot be forecast, the run fails with the reason rather than returning numbers that don't add up.  If you just want independent forecasts per slice — no coherent roll-up — the batch endpoint with per-series identifiers or `tenant_context` is simpler and tolerates per-series failure. 

        :param grouped_forecast_request: (required)
        :type grouped_forecast_request: GroupedForecastRequest
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._create_grouped_forecast_serialize(
            grouped_forecast_request=grouped_forecast_request,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '202': "GroupedForecastAccepted",
            '401': "ErrorResponse",
            '422': "ValidationFailedResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def create_grouped_forecast_without_preload_content(
        self,
        grouped_forecast_request: GroupedForecastRequest,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Submit a grouped (hierarchical) forecast with reconciliation

        Forecast a set of related series that roll up to a total — MRR by plan and region, demand by warehouse, revenue by category — and get back one coherent result: every parent equals the sum of its children, in every period, at every level.  You send only the **leaves** of the hierarchy (every combination of the declared dimensions, each with its own history). The API derives every aggregate level and the grand total by summing the leaf histories, forecasts the nodes, reconciles them to coherence, and stores each node as its own entity with independently tracked accuracy.  Processing is **asynchronous**: submission returns `202` with an id to poll via `GET /v2/forecast/grouped/{grouped_forecast_id}`. The run executes in the background as one all-or-nothing job — a hierarchy is one coherent answer, so there is no partial success. If any node cannot be forecast, the run fails with the reason rather than returning numbers that don't add up.  If you just want independent forecasts per slice — no coherent roll-up — the batch endpoint with per-series identifiers or `tenant_context` is simpler and tolerates per-series failure. 

        :param grouped_forecast_request: (required)
        :type grouped_forecast_request: GroupedForecastRequest
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._create_grouped_forecast_serialize(
            grouped_forecast_request=grouped_forecast_request,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '202': "GroupedForecastAccepted",
            '401': "ErrorResponse",
            '422': "ValidationFailedResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _create_grouped_forecast_serialize(
        self,
        grouped_forecast_request,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        # process the header parameters
        # process the form parameters
        # process the body parameter
        if grouped_forecast_request is not None:
            _body_params = grouped_forecast_request


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )

        # set the HTTP header `Content-Type`
        if _content_type:
            _header_params['Content-Type'] = _content_type
        else:
            _default_content_type = (
                self.api_client.select_header_content_type(
                    [
                        'application/json'
                    ]
                )
            )
            if _default_content_type is not None:
                _header_params['Content-Type'] = _default_content_type

        # authentication setting
        _auth_settings: List[str] = [
            'apiKey'
        ]

        return self.api_client.param_serialize(
            method='POST',
            resource_path='/v2/forecast/grouped',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def get_grouped_forecast(
        self,
        grouped_forecast_id: Annotated[StrictStr, Field(description="The id returned by POST /v2/forecast/grouped")],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> GroupedForecastStatusResponse:
        """Poll a grouped forecast for status and results

        Returns the run's status. Once `completed`, `results` carries a node map keyed by segment (`total`, `region=eu`, `plan=pro|region=eu`, …) — every node with its own forecast rows, its place in the tree, and the reconciliation details. If the run `failed`, `error` carries the reason and `results` stays null. 

        :param grouped_forecast_id: The id returned by POST /v2/forecast/grouped (required)
        :type grouped_forecast_id: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_grouped_forecast_serialize(
            grouped_forecast_id=grouped_forecast_id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "GroupedForecastStatusResponse",
            '401': "ErrorResponse",
            '404': "GetGroupedForecast404Response",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def get_grouped_forecast_with_http_info(
        self,
        grouped_forecast_id: Annotated[StrictStr, Field(description="The id returned by POST /v2/forecast/grouped")],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[GroupedForecastStatusResponse]:
        """Poll a grouped forecast for status and results

        Returns the run's status. Once `completed`, `results` carries a node map keyed by segment (`total`, `region=eu`, `plan=pro|region=eu`, …) — every node with its own forecast rows, its place in the tree, and the reconciliation details. If the run `failed`, `error` carries the reason and `results` stays null. 

        :param grouped_forecast_id: The id returned by POST /v2/forecast/grouped (required)
        :type grouped_forecast_id: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_grouped_forecast_serialize(
            grouped_forecast_id=grouped_forecast_id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "GroupedForecastStatusResponse",
            '401': "ErrorResponse",
            '404': "GetGroupedForecast404Response",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def get_grouped_forecast_without_preload_content(
        self,
        grouped_forecast_id: Annotated[StrictStr, Field(description="The id returned by POST /v2/forecast/grouped")],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Poll a grouped forecast for status and results

        Returns the run's status. Once `completed`, `results` carries a node map keyed by segment (`total`, `region=eu`, `plan=pro|region=eu`, …) — every node with its own forecast rows, its place in the tree, and the reconciliation details. If the run `failed`, `error` carries the reason and `results` stays null. 

        :param grouped_forecast_id: The id returned by POST /v2/forecast/grouped (required)
        :type grouped_forecast_id: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_grouped_forecast_serialize(
            grouped_forecast_id=grouped_forecast_id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "GroupedForecastStatusResponse",
            '401': "ErrorResponse",
            '404': "GetGroupedForecast404Response",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _get_grouped_forecast_serialize(
        self,
        grouped_forecast_id,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if grouped_forecast_id is not None:
            _path_params['grouped_forecast_id'] = grouped_forecast_id
        # process the query parameters
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'apiKey'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/v2/forecast/grouped/{grouped_forecast_id}',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )


