# coding: utf-8

"""
    ForecastAPI

    Time series forecasting service with multiple algorithms and automatic method selection

    The version of the OpenAPI document: 2.0.0
    Contact: support@forecastapi.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class AccumulatedForecastAssumptions(BaseModel):
    """
    The assumptions behind the total and its band, stated explicitly
    """ # noqa: E501
    correlation: Optional[Union[StrictFloat, StrictInt]] = None
    correlation_source: Optional[StrictStr] = None
    measured: Optional[StrictBool] = Field(default=None, description="True only when the correlation in force is our measured default — a caller-supplied value is never labelled measured")
    basis: Optional[StrictStr] = Field(default=None, description="The statistical model behind the total's band")
    decay: Optional[Union[StrictFloat, StrictInt]] = None
    discount_rate: Optional[Union[StrictFloat, StrictInt]] = None
    periods_per_year: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="How the annual discount rate was converted to the series frequency")
    timing: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["correlation", "correlation_source", "measured", "basis", "decay", "discount_rate", "periods_per_year", "timing"]

    @field_validator('correlation_source')
    def correlation_source_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['default', 'request']):
            raise ValueError("must be one of enum values ('default', 'request')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AccumulatedForecastAssumptions from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AccumulatedForecastAssumptions from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "correlation": obj.get("correlation"),
            "correlation_source": obj.get("correlation_source"),
            "measured": obj.get("measured"),
            "basis": obj.get("basis"),
            "decay": obj.get("decay"),
            "discount_rate": obj.get("discount_rate"),
            "periods_per_year": obj.get("periods_per_year"),
            "timing": obj.get("timing")
        })
        return _obj


