# coding: utf-8

"""
    ForecastAPI

    Time series forecasting service with multiple algorithms and automatic method selection

    The version of the OpenAPI document: 2.1.0
    Contact: support@forecastapi.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from forecastapi.models.accumulated_forecast_assumptions import AccumulatedForecastAssumptions
from forecastapi.models.accumulated_forecast_by_period_inner import AccumulatedForecastByPeriodInner
from typing import Optional, Set
from typing_extensions import Self

class AccumulatedForecast(BaseModel):
    """
    Cumulative projection over the forecast path. Present only when `accumulate` was sent, as a sibling of `result`. 
    """ # noqa: E501
    total: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Σ (value × survival × discount) over the horizon. Null when a period lacks a usable point forecast (see `total_reason`).")
    total_reason: Optional[StrictStr] = Field(default=None, description="Why `total` is null; null when the total is usable")
    lower: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Lower bound of the total under the stated correlation assumption. Null with an `interval_reason` when any period lacks a band or its coverage is unknown — rather than a band built from a partial set of variances. ")
    upper: Optional[Union[StrictFloat, StrictInt]] = None
    interval_reason: Optional[StrictStr] = Field(default=None, description="Why the total's band is absent; null when the band is present")
    confidence_level: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Coverage the total's band targets")
    path: Optional[StrictStr] = Field(default=None, description="Which path was accumulated — `adjusted` when `adjustments` was also sent, otherwise `baseline`")
    assumptions: Optional[AccumulatedForecastAssumptions] = None
    by_period: Optional[List[AccumulatedForecastByPeriodInner]] = Field(default=None, description="Running accumulation per period — `cumulative` through period L is the number a lead-time/safety-stock calculation reads")
    __properties: ClassVar[List[str]] = ["total", "total_reason", "lower", "upper", "interval_reason", "confidence_level", "path", "assumptions", "by_period"]

    @field_validator('path')
    def path_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['baseline', 'adjusted']):
            raise ValueError("must be one of enum values ('baseline', 'adjusted')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AccumulatedForecast from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of assumptions
        if self.assumptions:
            _dict['assumptions'] = self.assumptions.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in by_period (list)
        _items = []
        if self.by_period:
            for _item_by_period in self.by_period:
                if _item_by_period:
                    _items.append(_item_by_period.to_dict())
            _dict['by_period'] = _items
        # set to None if total (nullable) is None
        # and model_fields_set contains the field
        if self.total is None and "total" in self.model_fields_set:
            _dict['total'] = None

        # set to None if total_reason (nullable) is None
        # and model_fields_set contains the field
        if self.total_reason is None and "total_reason" in self.model_fields_set:
            _dict['total_reason'] = None

        # set to None if lower (nullable) is None
        # and model_fields_set contains the field
        if self.lower is None and "lower" in self.model_fields_set:
            _dict['lower'] = None

        # set to None if upper (nullable) is None
        # and model_fields_set contains the field
        if self.upper is None and "upper" in self.model_fields_set:
            _dict['upper'] = None

        # set to None if interval_reason (nullable) is None
        # and model_fields_set contains the field
        if self.interval_reason is None and "interval_reason" in self.model_fields_set:
            _dict['interval_reason'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AccumulatedForecast from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "total": obj.get("total"),
            "total_reason": obj.get("total_reason"),
            "lower": obj.get("lower"),
            "upper": obj.get("upper"),
            "interval_reason": obj.get("interval_reason"),
            "confidence_level": obj.get("confidence_level"),
            "path": obj.get("path"),
            "assumptions": AccumulatedForecastAssumptions.from_dict(obj["assumptions"]) if obj.get("assumptions") is not None else None,
            "by_period": [AccumulatedForecastByPeriodInner.from_dict(_item) for _item in obj["by_period"]] if obj.get("by_period") is not None else None
        })
        return _obj


