# coding: utf-8

"""
    ForecastAPI

    Time series forecasting service with multiple algorithms and automatic method selection

    The version of the OpenAPI document: 2.1.0
    Contact: support@forecastapi.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import date
from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class AccumulatedForecastByPeriodInner(BaseModel):
    """
    AccumulatedForecastByPeriodInner
    """ # noqa: E501
    var_date: Optional[date] = Field(default=None, alias="date")
    weight: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="survival × discount weight applied to this period (period 1 is 1.0)")
    cumulative: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Running weighted total through this period")
    cumulative_lower: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Running lower bound; present only when every period so far has a usable band")
    cumulative_upper: Optional[Union[StrictFloat, StrictInt]] = None
    __properties: ClassVar[List[str]] = ["date", "weight", "cumulative", "cumulative_lower", "cumulative_upper"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AccumulatedForecastByPeriodInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AccumulatedForecastByPeriodInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "date": obj.get("date"),
            "weight": obj.get("weight"),
            "cumulative": obj.get("cumulative"),
            "cumulative_lower": obj.get("cumulative_lower"),
            "cumulative_upper": obj.get("cumulative_upper")
        })
        return _obj


