# coding: utf-8

"""
    ForecastAPI

    Time series forecasting service with multiple algorithms and automatic method selection

    The version of the OpenAPI document: 2.1.0
    Contact: support@forecastapi.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool
from typing import Any, ClassVar, Dict, List, Optional
from forecastapi.models.adjusted_forecast_adjustments_applied_inner import AdjustedForecastAdjustmentsAppliedInner
from forecastapi.models.forecast_period import ForecastPeriod
from typing import Optional, Set
from typing_extensions import Self

class AdjustedForecast(BaseModel):
    """
    The what-if scenario path. Present only when `adjustments` was sent, as a sibling of `result` — never a field inside it. The adjusted path is never stored, so scenarios cannot pollute accuracy tracking. 
    """ # noqa: E501
    forecasts: Optional[List[ForecastPeriod]] = Field(default=None, description="The baseline path with every adjustment applied, in array order")
    adjustments_applied: Optional[List[AdjustedForecastAdjustmentsAppliedInner]] = Field(default=None, description="Echo of each adjustment as applied, in order")
    stored: Optional[StrictBool] = Field(default=None, description="Always false — only the baseline in `result` is persisted and scored for accuracy")
    __properties: ClassVar[List[str]] = ["forecasts", "adjustments_applied", "stored"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AdjustedForecast from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in forecasts (list)
        _items = []
        if self.forecasts:
            for _item_forecasts in self.forecasts:
                if _item_forecasts:
                    _items.append(_item_forecasts.to_dict())
            _dict['forecasts'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in adjustments_applied (list)
        _items = []
        if self.adjustments_applied:
            for _item_adjustments_applied in self.adjustments_applied:
                if _item_adjustments_applied:
                    _items.append(_item_adjustments_applied.to_dict())
            _dict['adjustments_applied'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AdjustedForecast from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "forecasts": [ForecastPeriod.from_dict(_item) for _item in obj["forecasts"]] if obj.get("forecasts") is not None else None,
            "adjustments_applied": [AdjustedForecastAdjustmentsAppliedInner.from_dict(_item) for _item in obj["adjustments_applied"]] if obj.get("adjustments_applied") is not None else None,
            "stored": obj.get("stored")
        })
        return _obj


