# coding: utf-8

"""
    ForecastAPI

    Time series forecasting service with multiple algorithms and automatic method selection

    The version of the OpenAPI document: 2.2.0
    Contact: support@forecastapi.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class AnomalyDetectionRequestAllOfAnomalySettings(BaseModel):
    """
    Optional detection configuration; omit for automatic method selection
    """ # noqa: E501
    method: Optional[StrictStr] = Field(default='auto', description="Detection method; auto picks the best fit for the data's characteristics")
    threshold: Optional[Union[Annotated[float, Field(le=5.0, strict=True, ge=0.5)], Annotated[int, Field(le=5, strict=True, ge=1)]]] = Field(default=None, description="Z-score threshold for the zscore method")
    multiplier: Optional[Union[Annotated[float, Field(le=5.0, strict=True, ge=0.5)], Annotated[int, Field(le=5, strict=True, ge=1)]]] = Field(default=None, description="IQR multiplier for the iqr method")
    seasonal_period: Optional[Annotated[int, Field(le=365, strict=True, ge=2)]] = Field(default=None, description="Season length for the seasonal method; detected automatically when omitted")
    minimum_periods: Optional[Annotated[int, Field(le=100, strict=True, ge=3)]] = Field(default=None, description="Minimum data points required before detection runs")
    __properties: ClassVar[List[str]] = ["method", "threshold", "multiplier", "seasonal_period", "minimum_periods"]

    @field_validator('method')
    def method_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['auto', 'zscore', 'iqr', 'seasonal']):
            raise ValueError("must be one of enum values ('auto', 'zscore', 'iqr', 'seasonal')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AnomalyDetectionRequestAllOfAnomalySettings from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AnomalyDetectionRequestAllOfAnomalySettings from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "method": obj.get("method") if obj.get("method") is not None else 'auto',
            "threshold": obj.get("threshold"),
            "multiplier": obj.get("multiplier"),
            "seasonal_period": obj.get("seasonal_period"),
            "minimum_periods": obj.get("minimum_periods")
        })
        return _obj


