# coding: utf-8

"""
    ForecastAPI

    Time series forecasting service with multiple algorithms and automatic method selection

    The version of the OpenAPI document: 2.2.0
    Contact: support@forecastapi.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from forecastapi.models.auto_selection_scores_value import AutoSelectionScoresValue
from typing import Optional, Set
from typing_extensions import Self

class AutoSelection(BaseModel):
    """
    Present only when `model: auto` was requested — which model actually answered, and why. On /v2/forecast and batch results it appears inside `model_info`; on /v2/inventory-planning and /v2/traffic-forecasting it appears under `meta`. 
    """ # noqa: E501
    requested: Optional[StrictStr] = None
    selected: Optional[StrictStr] = Field(default=None, description="The model that produced this response")
    reason: Optional[StrictStr] = Field(default=None, description="Why this model was selected. `scored_winner` means one model beat every alternative by a clear margin on realized accuracy for this identifier; everything else means the evidence-gathering default was served. ")
    scores: Optional[Dict[str, AutoSelectionScoresValue]] = Field(default=None, description="Per-model realized-accuracy scorecard for this identifier, when one exists")
    __properties: ClassVar[List[str]] = ["requested", "selected", "reason", "scores"]

    @field_validator('reason')
    def reason_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['no_history', 'insufficient_evidence', 'no_clear_winner', 'scored_winner']):
            raise ValueError("must be one of enum values ('no_history', 'insufficient_evidence', 'no_clear_winner', 'scored_winner')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AutoSelection from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each value in scores (dict)
        _field_dict = {}
        if self.scores:
            for _key_scores in self.scores:
                if self.scores[_key_scores]:
                    _field_dict[_key_scores] = self.scores[_key_scores].to_dict()
            _dict['scores'] = _field_dict
        # set to None if scores (nullable) is None
        # and model_fields_set contains the field
        if self.scores is None and "scores" in self.model_fields_set:
            _dict['scores'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AutoSelection from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "requested": obj.get("requested"),
            "selected": obj.get("selected"),
            "reason": obj.get("reason"),
            "scores": dict(
                (_k, AutoSelectionScoresValue.from_dict(_v))
                for _k, _v in obj["scores"].items()
            )
            if obj.get("scores") is not None
            else None
        })
        return _obj


