# coding: utf-8

"""
    ForecastAPI

    Time series forecasting service with multiple algorithms and automatic method selection

    The version of the OpenAPI document: 2.0.2
    Contact: support@forecastapi.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from forecastapi.models.accumulate_options import AccumulateOptions
from forecastapi.models.adjustments_inner import AdjustmentsInner
from forecastapi.models.batch_forecast_series_data_inner import BatchForecastSeriesDataInner
from forecastapi.models.value_bounds import ValueBounds
from typing import Optional, Set
from typing_extensions import Self

class BatchForecastSeries(BaseModel):
    """
    BatchForecastSeries
    """ # noqa: E501
    identifier: StrictStr = Field(description="SKU, Product ID, or other identifier for this series")
    tenant_context: Optional[StrictStr] = Field(default=None, description="Optional segmentation dimension — the same identifier may appear under several tenant_context values in one batch")
    data: Annotated[List[BatchForecastSeriesDataInner], Field(min_length=2)] = Field(description="Historical data for this series (at most 1,000 points per series on the free tier)")
    periods: Optional[Annotated[int, Field(le=365, strict=True, ge=1)]] = Field(default=None, description="Override of the request-level horizon for this series")
    frequency: Optional[StrictStr] = Field(default=None, description="Override of the request-level frequency")
    data_type: Optional[Annotated[str, Field(strict=True, max_length=50)]] = Field(default=None, description="Override of the request-level data type")
    confidence: Optional[Union[Annotated[float, Field(le=0.99, strict=True, ge=0.1)], Annotated[int, Field(le=0, strict=True, ge=1)]]] = Field(default=None, description="Override of the request-level confidence")
    confidence_level: Optional[Union[Annotated[float, Field(le=0.99, strict=True, ge=0.1)], Annotated[int, Field(le=0, strict=True, ge=1)]]] = Field(default=None, description="Alias for `confidence`")
    quantiles: Optional[Annotated[List[Union[StrictFloat, StrictInt]], Field(min_length=1, max_length=9)]] = Field(default=None, description="Decile levels to return per period — only deciles between 0.1 and 0.9 are accepted, because those are the levels every backend produces natively; anything finer would be interpolation served under a label the model never predicted. Adds a `quantiles` object to each forecast row alongside the usual bounds. Honoured by /v2/forecast and /v2/batch/forecast (request-level default or per-series override); rejected on grouped forecasts; ignored by other endpoints sharing this request shape. ")
    value_bounds: Optional[ValueBounds] = None
    adjustments: Optional[Annotated[List[AdjustmentsInner], Field(min_length=1, max_length=20)]] = Field(default=None, description="What-if scenario applied on top of the forecast (\"assume we lose the enterprise deal\"). Adjustments compose in array order — ×2 then +50 is not +50 then ×2. Each one moves the point, both bounds and any quantile fan together. Returns an `adjusted` block; the adjusted path is never stored or accuracy-tracked. Honoured by /v2/forecast and /v2/batch/forecast (request-level default or per-series override — period windows are checked against each series' own horizon); rejected on grouped forecasts; ignored by other endpoints sharing this request shape. ")
    accumulate: Optional[AccumulateOptions] = None
    __properties: ClassVar[List[str]] = ["identifier", "tenant_context", "data", "periods", "frequency", "data_type", "confidence", "confidence_level", "quantiles", "value_bounds", "adjustments", "accumulate"]

    @field_validator('frequency')
    def frequency_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['H', 'D', 'W', 'M', 'MS', 'ME', 'Q', 'Y']):
            raise ValueError("must be one of enum values ('H', 'D', 'W', 'M', 'MS', 'ME', 'Q', 'Y')")
        return value

    @field_validator('quantiles')
    def quantiles_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        for i in value:
            if i not in set([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]):
                raise ValueError("each list item must be one of (0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9)")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of BatchForecastSeries from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in data (list)
        _items = []
        if self.data:
            for _item_data in self.data:
                if _item_data:
                    _items.append(_item_data.to_dict())
            _dict['data'] = _items
        # override the default output from pydantic by calling `to_dict()` of value_bounds
        if self.value_bounds:
            _dict['value_bounds'] = self.value_bounds.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in adjustments (list)
        _items = []
        if self.adjustments:
            for _item_adjustments in self.adjustments:
                if _item_adjustments:
                    _items.append(_item_adjustments.to_dict())
            _dict['adjustments'] = _items
        # override the default output from pydantic by calling `to_dict()` of accumulate
        if self.accumulate:
            _dict['accumulate'] = self.accumulate.to_dict()
        # set to None if tenant_context (nullable) is None
        # and model_fields_set contains the field
        if self.tenant_context is None and "tenant_context" in self.model_fields_set:
            _dict['tenant_context'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of BatchForecastSeries from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "identifier": obj.get("identifier"),
            "tenant_context": obj.get("tenant_context"),
            "data": [BatchForecastSeriesDataInner.from_dict(_item) for _item in obj["data"]] if obj.get("data") is not None else None,
            "periods": obj.get("periods"),
            "frequency": obj.get("frequency"),
            "data_type": obj.get("data_type"),
            "confidence": obj.get("confidence"),
            "confidence_level": obj.get("confidence_level"),
            "quantiles": obj.get("quantiles"),
            "value_bounds": ValueBounds.from_dict(obj["value_bounds"]) if obj.get("value_bounds") is not None else None,
            "adjustments": [AdjustmentsInner.from_dict(_item) for _item in obj["adjustments"]] if obj.get("adjustments") is not None else None,
            "accumulate": AccumulateOptions.from_dict(obj["accumulate"]) if obj.get("accumulate") is not None else None
        })
        return _obj


