# coding: utf-8

"""
    ForecastAPI

    Time series forecasting service with multiple algorithms and automatic method selection

    The version of the OpenAPI document: 2.0.3
    Contact: support@forecastapi.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict
from typing import Any, ClassVar, Dict, List, Optional
from forecastapi.models.accumulated_forecast import AccumulatedForecast
from forecastapi.models.adjusted_forecast import AdjustedForecast
from forecastapi.models.forecast_response_meta import ForecastResponseMeta
from forecastapi.models.forecast_response_result import ForecastResponseResult
from typing import Optional, Set
from typing_extensions import Self

class ForecastResponse(BaseModel):
    """
    ForecastResponse
    """ # noqa: E501
    result: Optional[ForecastResponseResult] = None
    adjusted: Optional[AdjustedForecast] = None
    accumulated: Optional[AccumulatedForecast] = None
    meta: Optional[ForecastResponseMeta] = None
    __properties: ClassVar[List[str]] = ["result", "adjusted", "accumulated", "meta"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ForecastResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of result
        if self.result:
            _dict['result'] = self.result.to_dict()
        # override the default output from pydantic by calling `to_dict()` of adjusted
        if self.adjusted:
            _dict['adjusted'] = self.adjusted.to_dict()
        # override the default output from pydantic by calling `to_dict()` of accumulated
        if self.accumulated:
            _dict['accumulated'] = self.accumulated.to_dict()
        # override the default output from pydantic by calling `to_dict()` of meta
        if self.meta:
            _dict['meta'] = self.meta.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ForecastResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "result": ForecastResponseResult.from_dict(obj["result"]) if obj.get("result") is not None else None,
            "adjusted": AdjustedForecast.from_dict(obj["adjusted"]) if obj.get("adjusted") is not None else None,
            "accumulated": AccumulatedForecast.from_dict(obj["accumulated"]) if obj.get("accumulated") is not None else None,
            "meta": ForecastResponseMeta.from_dict(obj["meta"]) if obj.get("meta") is not None else None
        })
        return _obj


