# coding: utf-8

"""
    ForecastAPI

    Time series forecasting service with multiple algorithms and automatic method selection

    The version of the OpenAPI document: 2.1.0
    Contact: support@forecastapi.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import date
from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from forecastapi.models.accumulate_options import AccumulateOptions
from forecastapi.models.adjustments_inner import AdjustmentsInner
from forecastapi.models.forecast_request_data_inner import ForecastRequestDataInner
from forecastapi.models.value_bounds import ValueBounds
from typing import Optional, Set
from typing_extensions import Self

class ForecastRequest(BaseModel):
    """
    ForecastRequest
    """ # noqa: E501
    identifier: StrictStr = Field(description="SKU, Product ID, or other identifier for the data series")
    tenant_context: Optional[StrictStr] = Field(default=None, description="Optional segmentation dimension. A series is identified by the pair identifier + tenant_context, so \"mrr\" on \"plan-pro\" and \"mrr\" on \"plan-free\" are two independent series, each with its own history and accuracy tracking. Despite the name it isn't only for multi-tenancy — use it for any slice: plan, region, store, channel, cohort, device type. ")
    frequency: StrictStr = Field(description="Data frequency: - H: Hourly - D: Daily - W: Weekly - M: Monthly (end of month) - MS: Monthly (start of month) - ME: Monthly (end of month) - Q: Quarterly - Y: Yearly ")
    start_date: Optional[date] = Field(default=None, description="Optional start date for the forecast")
    data_type: StrictStr = Field(description="Type of data (e.g., sales, demand, inventory, web_traffic)")
    periods: Annotated[int, Field(strict=True, ge=1)] = Field(description="Number of periods to forecast")
    model: Optional[StrictStr] = Field(default='standard', description="Which forecasting engine to use. The advanced variants and ensemble provide higher accuracy at a higher usage cost than standard. ")
    confidence_level: Optional[Union[Annotated[float, Field(le=0.99, strict=True, ge=0.1)], Annotated[int, Field(le=0, strict=True, ge=1)]]] = Field(default=0.8, description="Confidence level for the prediction interval. Note that 0.80 is the widest band the foundation models (advanced-quantized, advanced-patched, ensemble) produce natively — for genuinely distinct levels beyond that, request a quantile fan via `quantiles` instead of repeating the call at several confidence levels. ")
    quantiles: Optional[Annotated[List[Union[StrictFloat, StrictInt]], Field(min_length=1, max_length=9)]] = Field(default=None, description="Decile levels to return per period — only deciles between 0.1 and 0.9 are accepted, because those are the levels every backend produces natively; anything finer would be interpolation served under a label the model never predicted. Adds a `quantiles` object to each forecast row alongside the usual bounds. Honoured by /v2/forecast and /v2/batch/forecast (request-level default or per-series override); rejected on grouped forecasts; ignored by other endpoints sharing this request shape. ")
    value_bounds: Optional[ValueBounds] = None
    adjustments: Optional[Annotated[List[AdjustmentsInner], Field(min_length=1, max_length=20)]] = Field(default=None, description="What-if scenario applied on top of the forecast (\"assume we lose the enterprise deal\"). Adjustments compose in array order — ×2 then +50 is not +50 then ×2. Each one moves the point, both bounds and any quantile fan together. Returns an `adjusted` block; the adjusted path is never stored or accuracy-tracked. Honoured by /v2/forecast and /v2/batch/forecast (request-level default or per-series override — period windows are checked against each series' own horizon); rejected on grouped forecasts; ignored by other endpoints sharing this request shape. ")
    accumulate: Optional[AccumulateOptions] = None
    selection_metric: Optional[StrictStr] = Field(default=None, description="Which back-testing error metric decides the winning model when candidates are compared: - auto: combined for demand/sales/inventory, sMAPE otherwise (default) - combined: 0.6·MASE + 0.4·sMAPE — balances accuracy and trend capture - mase: Mean Absolute Scaled Error — accuracy relative to a naive forecast - smape: Symmetric Mean Absolute Percentage Error ")
    data: Annotated[List[ForecastRequestDataInner], Field(min_length=1)] = Field(description="Historical time series data")
    __properties: ClassVar[List[str]] = ["identifier", "tenant_context", "frequency", "start_date", "data_type", "periods", "model", "confidence_level", "quantiles", "value_bounds", "adjustments", "accumulate", "selection_metric", "data"]

    @field_validator('frequency')
    def frequency_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['H', 'D', 'W', 'M', 'MS', 'ME', 'Q', 'Y']):
            raise ValueError("must be one of enum values ('H', 'D', 'W', 'M', 'MS', 'ME', 'Q', 'Y')")
        return value

    @field_validator('model')
    def model_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['standard', 'advanced', 'advanced-quantized', 'advanced-patched', 'ensemble']):
            raise ValueError("must be one of enum values ('standard', 'advanced', 'advanced-quantized', 'advanced-patched', 'ensemble')")
        return value

    @field_validator('quantiles')
    def quantiles_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        for i in value:
            if i not in set([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]):
                raise ValueError("each list item must be one of (0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9)")
        return value

    @field_validator('selection_metric')
    def selection_metric_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['auto', 'combined', 'mase', 'smape']):
            raise ValueError("must be one of enum values ('auto', 'combined', 'mase', 'smape')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ForecastRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of value_bounds
        if self.value_bounds:
            _dict['value_bounds'] = self.value_bounds.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in adjustments (list)
        _items = []
        if self.adjustments:
            for _item_adjustments in self.adjustments:
                if _item_adjustments:
                    _items.append(_item_adjustments.to_dict())
            _dict['adjustments'] = _items
        # override the default output from pydantic by calling `to_dict()` of accumulate
        if self.accumulate:
            _dict['accumulate'] = self.accumulate.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in data (list)
        _items = []
        if self.data:
            for _item_data in self.data:
                if _item_data:
                    _items.append(_item_data.to_dict())
            _dict['data'] = _items
        # set to None if tenant_context (nullable) is None
        # and model_fields_set contains the field
        if self.tenant_context is None and "tenant_context" in self.model_fields_set:
            _dict['tenant_context'] = None

        # set to None if start_date (nullable) is None
        # and model_fields_set contains the field
        if self.start_date is None and "start_date" in self.model_fields_set:
            _dict['start_date'] = None

        # set to None if selection_metric (nullable) is None
        # and model_fields_set contains the field
        if self.selection_metric is None and "selection_metric" in self.model_fields_set:
            _dict['selection_metric'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ForecastRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "identifier": obj.get("identifier"),
            "tenant_context": obj.get("tenant_context"),
            "frequency": obj.get("frequency"),
            "start_date": obj.get("start_date"),
            "data_type": obj.get("data_type"),
            "periods": obj.get("periods"),
            "model": obj.get("model") if obj.get("model") is not None else 'standard',
            "confidence_level": obj.get("confidence_level") if obj.get("confidence_level") is not None else 0.8,
            "quantiles": obj.get("quantiles"),
            "value_bounds": ValueBounds.from_dict(obj["value_bounds"]) if obj.get("value_bounds") is not None else None,
            "adjustments": [AdjustmentsInner.from_dict(_item) for _item in obj["adjustments"]] if obj.get("adjustments") is not None else None,
            "accumulate": AccumulateOptions.from_dict(obj["accumulate"]) if obj.get("accumulate") is not None else None,
            "selection_metric": obj.get("selection_metric"),
            "data": [ForecastRequestDataInner.from_dict(_item) for _item in obj["data"]] if obj.get("data") is not None else None
        })
        return _obj


