# coding: utf-8

"""
    ForecastAPI

    Time series forecasting service with multiple algorithms and automatic method selection

    The version of the OpenAPI document: 2.0.0
    Contact: support@forecastapi.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from forecastapi.models.forecast_period import ForecastPeriod
from typing import Optional, Set
from typing_extensions import Self

class GroupedForecastNode(BaseModel):
    """
    GroupedForecastNode
    """ # noqa: E501
    identifier: Optional[StrictStr] = Field(default=None, description="The measure — the same for every node")
    segment: Optional[Dict[str, Any]] = Field(default=None, description="The dimension values this node covers — empty for the total, all declared dimensions for a leaf")
    level: Optional[StrictInt] = Field(default=None, description="Depth in the tree; 0 is the total")
    is_leaf: Optional[StrictBool] = None
    parent: Optional[StrictStr] = Field(default=None, description="Segment key of the parent node; null for the total")
    children: Optional[List[StrictStr]] = Field(default=None, description="Segment keys of the children; empty for leaves")
    forecasts: Optional[List[ForecastPeriod]] = Field(default=None, description="The reconciled path — this is what is stored and accuracy-tracked per node")
    model_info: Optional[Dict[str, Any]] = Field(default=None, description="Method and reconciliation details for this node. With min_trace, the node's unreconciled path is reported under `reconciliation.base_forecast`. When an aggregate band cannot be built honestly (a child's band coverage is unknown), the band is omitted and `reconciliation.interval_reason` states why. ")
    __properties: ClassVar[List[str]] = ["identifier", "segment", "level", "is_leaf", "parent", "children", "forecasts", "model_info"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GroupedForecastNode from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in forecasts (list)
        _items = []
        if self.forecasts:
            for _item_forecasts in self.forecasts:
                if _item_forecasts:
                    _items.append(_item_forecasts.to_dict())
            _dict['forecasts'] = _items
        # set to None if parent (nullable) is None
        # and model_fields_set contains the field
        if self.parent is None and "parent" in self.model_fields_set:
            _dict['parent'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GroupedForecastNode from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "identifier": obj.get("identifier"),
            "segment": obj.get("segment"),
            "level": obj.get("level"),
            "is_leaf": obj.get("is_leaf"),
            "parent": obj.get("parent"),
            "children": obj.get("children"),
            "forecasts": [ForecastPeriod.from_dict(_item) for _item in obj["forecasts"]] if obj.get("forecasts") is not None else None,
            "model_info": obj.get("model_info")
        })
        return _obj


