# coding: utf-8

"""
    ForecastAPI

    Time series forecasting service with multiple algorithms and automatic method selection

    The version of the OpenAPI document: 2.2.0
    Contact: support@forecastapi.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from forecastapi.models.grouped_forecast_series import GroupedForecastSeries
from typing import Optional, Set
from typing_extensions import Self

class GroupedForecastRequest(BaseModel):
    """
    Configuration is request-level only: every node of a hierarchy must share `periods`, `frequency`, `model` and `confidence`, so per-series overrides are rejected rather than silently ignored. The planning parameters (`quantiles`, `value_bounds`, `adjustments`, `accumulate`) are not supported on grouped forecasts and are rejected explicitly. All series must end on the same date so forecast periods align; histories may start whenever they like — a segment that launched later simply contributes zero before its first data point. A request may expand to at most 250 nodes (leaves plus every derived aggregate and the total) across at most 4 hierarchy levels. 
    """ # noqa: E501
    identifier: StrictStr = Field(description="Names the measure being forecast (e.g. \"mrr\"). The hierarchy's total is stored under this identifier exactly like a plain /v2/forecast for it — the total of the hierarchy IS the measure. ")
    tenant_context: Optional[StrictStr] = Field(default=None, description="Optional tenant scope, independent of segment — tenancy keeps meaning \"whose data is this\", segment means \"which slice\". ")
    hierarchy: Annotated[List[Annotated[str, Field(strict=True, max_length=64)]], Field(min_length=1, max_length=4)] = Field(description="The dimensions of the hierarchy, outermost first. Each series' segment must name exactly these dimensions.")
    reconciliation: Optional[StrictStr] = Field(default='bottom_up', description="- bottom_up (default): only the leaves are forecast; every aggregate is the   exact sum of its children. Fast and cheap; best when leaf histories are   substantial enough to forecast well on their own. - min_trace: every node — aggregates included — is forecast, then MinTrace   optimally redistributes the disagreement between levels into a coherent set.   Costs one forecast per node, but lets the usually-smoother aggregate series   inform the result, which tends to help when leaves are short or noisy.  top_down is not supported and is rejected by name. ")
    correlation: Optional[Union[Annotated[float, Field(le=1, strict=True, ge=0)], Annotated[int, Field(le=1, strict=True, ge=0)]]] = Field(default=0.5, description="bottom_up only — the assumed correlation between sibling errors when building aggregate confidence bands. 0 = independent siblings, 1 = perfectly correlated (equivalent to summing the bounds). Echoed back in the response and never labelled as measured. ")
    frequency: StrictStr = Field(description="Data frequency, shared by every series in the hierarchy")
    periods: Annotated[int, Field(le=365, strict=True, ge=1)] = Field(description="Number of periods to forecast, shared by every node")
    data_type: Optional[Annotated[str, Field(strict=True, max_length=50)]] = Field(default='sales', description="Type of data (e.g., sales, demand, revenue). Sales-family types get non-negative reconciliation treatment.")
    model: Optional[StrictStr] = Field(default='standard', description="Forecasting engine used for every node. `auto` is not accepted here: it routes per series, and a hierarchy is reconciled under one model. ")
    confidence: Optional[Union[Annotated[float, Field(le=0.99, strict=True, ge=0.1)], Annotated[int, Field(le=0, strict=True, ge=1)]]] = Field(default=0.8, description="Confidence level for prediction intervals, shared by every node")
    confidence_level: Optional[Union[Annotated[float, Field(le=0.99, strict=True, ge=0.1)], Annotated[int, Field(le=0, strict=True, ge=1)]]] = Field(default=None, description="Alias for `confidence`; if both are sent, `confidence` wins")
    series: Annotated[List[GroupedForecastSeries], Field(min_length=2, max_length=200)] = Field(description="The leaves of the hierarchy — one entry per combination of dimension values, each combination exactly once. Up to 200 series on a paid plan, 10 on the free tier. Aggregate levels are derived by the API and must not be sent. ")
    __properties: ClassVar[List[str]] = ["identifier", "tenant_context", "hierarchy", "reconciliation", "correlation", "frequency", "periods", "data_type", "model", "confidence", "confidence_level", "series"]

    @field_validator('reconciliation')
    def reconciliation_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['bottom_up', 'min_trace']):
            raise ValueError("must be one of enum values ('bottom_up', 'min_trace')")
        return value

    @field_validator('frequency')
    def frequency_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['H', 'D', 'W', 'M', 'MS', 'ME', 'Q', 'Y']):
            raise ValueError("must be one of enum values ('H', 'D', 'W', 'M', 'MS', 'ME', 'Q', 'Y')")
        return value

    @field_validator('model')
    def model_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['standard', 'advanced', 'advanced-quantized', 'advanced-patched', 'ensemble']):
            raise ValueError("must be one of enum values ('standard', 'advanced', 'advanced-quantized', 'advanced-patched', 'ensemble')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GroupedForecastRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in series (list)
        _items = []
        if self.series:
            for _item_series in self.series:
                if _item_series:
                    _items.append(_item_series.to_dict())
            _dict['series'] = _items
        # set to None if tenant_context (nullable) is None
        # and model_fields_set contains the field
        if self.tenant_context is None and "tenant_context" in self.model_fields_set:
            _dict['tenant_context'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GroupedForecastRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "identifier": obj.get("identifier"),
            "tenant_context": obj.get("tenant_context"),
            "hierarchy": obj.get("hierarchy"),
            "reconciliation": obj.get("reconciliation") if obj.get("reconciliation") is not None else 'bottom_up',
            "correlation": obj.get("correlation") if obj.get("correlation") is not None else 0.5,
            "frequency": obj.get("frequency"),
            "periods": obj.get("periods"),
            "data_type": obj.get("data_type") if obj.get("data_type") is not None else 'sales',
            "model": obj.get("model") if obj.get("model") is not None else 'standard',
            "confidence": obj.get("confidence") if obj.get("confidence") is not None else 0.8,
            "confidence_level": obj.get("confidence_level"),
            "series": [GroupedForecastSeries.from_dict(_item) for _item in obj["series"]] if obj.get("series") is not None else None
        })
        return _obj


