# coding: utf-8

"""
    ForecastAPI

    Time series forecasting service with multiple algorithms and automatic method selection

    The version of the OpenAPI document: 2.2.0
    Contact: support@forecastapi.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class GroupedForecastAccepted(BaseModel):
    """
    GroupedForecastAccepted
    """ # noqa: E501
    grouped_forecast_id: Optional[StrictStr] = Field(default=None, description="Id to poll via GET /v2/forecast/grouped/{grouped_forecast_id}")
    status: Optional[StrictStr] = None
    series_count: Optional[StrictInt] = Field(default=None, description="Leaf series submitted")
    node_count: Optional[StrictInt] = Field(default=None, description="What will actually be forecast and reconciled — the leaves plus every derived aggregate and the total")
    reconciliation: Optional[StrictStr] = None
    time_taken_ms: Optional[Union[StrictFloat, StrictInt]] = None
    __properties: ClassVar[List[str]] = ["grouped_forecast_id", "status", "series_count", "node_count", "reconciliation", "time_taken_ms"]

    @field_validator('reconciliation')
    def reconciliation_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['bottom_up', 'min_trace']):
            raise ValueError("must be one of enum values ('bottom_up', 'min_trace')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GroupedForecastAccepted from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GroupedForecastAccepted from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "grouped_forecast_id": obj.get("grouped_forecast_id"),
            "status": obj.get("status"),
            "series_count": obj.get("series_count"),
            "node_count": obj.get("node_count"),
            "reconciliation": obj.get("reconciliation"),
            "time_taken_ms": obj.get("time_taken_ms")
        })
        return _obj


