# coding: utf-8

"""
    ForecastAPI

    Time series forecasting service with multiple algorithms and automatic method selection

    The version of the OpenAPI document: 2.0.0
    Contact: support@forecastapi.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Union
from typing_extensions import Annotated
from forecastapi.models.inventory_planning_request_inventory_settings_suppliers_inner import InventoryPlanningRequestInventorySettingsSuppliersInner
from typing import Optional, Set
from typing_extensions import Self

class InventoryPlanningRequestInventorySettings(BaseModel):
    """
    Current inventory status and supplier information
    """ # noqa: E501
    current_stock: Union[Annotated[float, Field(strict=True, ge=0)], Annotated[int, Field(strict=True, ge=0)]] = Field(description="Current quantity in stock")
    minimum_stock: Union[Annotated[float, Field(strict=True, ge=0)], Annotated[int, Field(strict=True, ge=0)]] = Field(description="Minimum stock level to maintain")
    service_level: Union[Annotated[float, Field(le=0.999, strict=True, ge=0.5)], Annotated[int, Field(le=0, strict=True, ge=1)]] = Field(description="Target service level (probability of not stocking out)")
    suppliers: Annotated[List[InventoryPlanningRequestInventorySettingsSuppliersInner], Field(min_length=1)] = Field(description="Available suppliers with their characteristics")
    __properties: ClassVar[List[str]] = ["current_stock", "minimum_stock", "service_level", "suppliers"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of InventoryPlanningRequestInventorySettings from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in suppliers (list)
        _items = []
        if self.suppliers:
            for _item_suppliers in self.suppliers:
                if _item_suppliers:
                    _items.append(_item_suppliers.to_dict())
            _dict['suppliers'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of InventoryPlanningRequestInventorySettings from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "current_stock": obj.get("current_stock"),
            "minimum_stock": obj.get("minimum_stock"),
            "service_level": obj.get("service_level"),
            "suppliers": [InventoryPlanningRequestInventorySettingsSuppliersInner.from_dict(_item) for _item in obj["suppliers"]] if obj.get("suppliers") is not None else None
        })
        return _obj


