# coding: utf-8

"""
    ForecastAPI

    Time series forecasting service with multiple algorithms and automatic method selection

    The version of the OpenAPI document: 2.0.2
    Contact: support@forecastapi.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from forecastapi.models.product_insight_recommendation import ProductInsightRecommendation
from typing import Optional, Set
from typing_extensions import Self

class ProductInsight(BaseModel):
    """
    ProductInsight
    """ # noqa: E501
    var_class: Optional[StrictStr] = Field(default=None, description="Insight family (e.g. margin, sales, cost, lead_time)", alias="class")
    type: Optional[StrictStr] = None
    severity: Optional[StrictStr] = None
    title: Optional[StrictStr] = None
    description: Optional[StrictStr] = None
    metrics: Optional[Dict[str, Any]] = Field(default=None, description="The numbers behind the insight")
    recommendation: Optional[ProductInsightRecommendation] = None
    confidence: Optional[StrictStr] = None
    var_date: Optional[StrictStr] = Field(default=None, alias="date")
    change_status: Optional[StrictStr] = Field(default=None, description="How this insight compares to the previous analysis of the same product — every insight is \"new\" on the first analysis")
    __properties: ClassVar[List[str]] = ["class", "type", "severity", "title", "description", "metrics", "recommendation", "confidence", "date", "change_status"]

    @field_validator('severity')
    def severity_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['critical', 'warning', 'info']):
            raise ValueError("must be one of enum values ('critical', 'warning', 'info')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ProductInsight from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of recommendation
        if self.recommendation:
            _dict['recommendation'] = self.recommendation.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ProductInsight from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "class": obj.get("class"),
            "type": obj.get("type"),
            "severity": obj.get("severity"),
            "title": obj.get("title"),
            "description": obj.get("description"),
            "metrics": obj.get("metrics"),
            "recommendation": ProductInsightRecommendation.from_dict(obj["recommendation"]) if obj.get("recommendation") is not None else None,
            "confidence": obj.get("confidence"),
            "date": obj.get("date"),
            "change_status": obj.get("change_status")
        })
        return _obj


