# coding: utf-8

"""
    ForecastAPI

    Time series forecasting service with multiple algorithms and automatic method selection

    The version of the OpenAPI document: 2.0.3
    Contact: support@forecastapi.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from forecastapi.models.product_insights_request_baseline_period_days import ProductInsightsRequestBaselinePeriodDays
from forecastapi.models.product_insights_request_cost_history_inner import ProductInsightsRequestCostHistoryInner
from forecastapi.models.product_insights_request_insight_settings import ProductInsightsRequestInsightSettings
from forecastapi.models.product_insights_request_purchases_inner import ProductInsightsRequestPurchasesInner
from forecastapi.models.product_insights_request_sales_inner import ProductInsightsRequestSalesInner
from typing import Optional, Set
from typing_extensions import Self

class ProductInsightsRequest(BaseModel):
    """
    At least one of `sales`, `purchases` or `cost_history` must be provided.
    """ # noqa: E501
    identifier: Annotated[str, Field(strict=True, max_length=255)] = Field(description="Product identifier")
    tenant_context: Optional[Annotated[str, Field(strict=True, max_length=255)]] = None
    product_name: Optional[Annotated[str, Field(strict=True, max_length=500)]] = None
    product_group_id: Optional[Annotated[str, Field(strict=True, max_length=255)]] = None
    base_currency: Optional[Annotated[str, Field(min_length=3, strict=True, max_length=3)]] = Field(default=None, description="ISO 4217 currency the analysis reports in")
    baseline_period_days: Optional[ProductInsightsRequestBaselinePeriodDays] = None
    locale: Optional[StrictStr] = Field(default='en', description="Locale for insight texts")
    sales: Optional[List[ProductInsightsRequestSalesInner]] = None
    purchases: Optional[List[ProductInsightsRequestPurchasesInner]] = None
    cost_history: Optional[List[ProductInsightsRequestCostHistoryInner]] = None
    insight_settings: Optional[ProductInsightsRequestInsightSettings] = None
    __properties: ClassVar[List[str]] = ["identifier", "tenant_context", "product_name", "product_group_id", "base_currency", "baseline_period_days", "locale", "sales", "purchases", "cost_history", "insight_settings"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ProductInsightsRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of baseline_period_days
        if self.baseline_period_days:
            _dict['baseline_period_days'] = self.baseline_period_days.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in sales (list)
        _items = []
        if self.sales:
            for _item_sales in self.sales:
                if _item_sales:
                    _items.append(_item_sales.to_dict())
            _dict['sales'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in purchases (list)
        _items = []
        if self.purchases:
            for _item_purchases in self.purchases:
                if _item_purchases:
                    _items.append(_item_purchases.to_dict())
            _dict['purchases'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in cost_history (list)
        _items = []
        if self.cost_history:
            for _item_cost_history in self.cost_history:
                if _item_cost_history:
                    _items.append(_item_cost_history.to_dict())
            _dict['cost_history'] = _items
        # override the default output from pydantic by calling `to_dict()` of insight_settings
        if self.insight_settings:
            _dict['insight_settings'] = self.insight_settings.to_dict()
        # set to None if tenant_context (nullable) is None
        # and model_fields_set contains the field
        if self.tenant_context is None and "tenant_context" in self.model_fields_set:
            _dict['tenant_context'] = None

        # set to None if product_name (nullable) is None
        # and model_fields_set contains the field
        if self.product_name is None and "product_name" in self.model_fields_set:
            _dict['product_name'] = None

        # set to None if product_group_id (nullable) is None
        # and model_fields_set contains the field
        if self.product_group_id is None and "product_group_id" in self.model_fields_set:
            _dict['product_group_id'] = None

        # set to None if base_currency (nullable) is None
        # and model_fields_set contains the field
        if self.base_currency is None and "base_currency" in self.model_fields_set:
            _dict['base_currency'] = None

        # set to None if sales (nullable) is None
        # and model_fields_set contains the field
        if self.sales is None and "sales" in self.model_fields_set:
            _dict['sales'] = None

        # set to None if purchases (nullable) is None
        # and model_fields_set contains the field
        if self.purchases is None and "purchases" in self.model_fields_set:
            _dict['purchases'] = None

        # set to None if cost_history (nullable) is None
        # and model_fields_set contains the field
        if self.cost_history is None and "cost_history" in self.model_fields_set:
            _dict['cost_history'] = None

        # set to None if insight_settings (nullable) is None
        # and model_fields_set contains the field
        if self.insight_settings is None and "insight_settings" in self.model_fields_set:
            _dict['insight_settings'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ProductInsightsRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "identifier": obj.get("identifier"),
            "tenant_context": obj.get("tenant_context"),
            "product_name": obj.get("product_name"),
            "product_group_id": obj.get("product_group_id"),
            "base_currency": obj.get("base_currency"),
            "baseline_period_days": ProductInsightsRequestBaselinePeriodDays.from_dict(obj["baseline_period_days"]) if obj.get("baseline_period_days") is not None else None,
            "locale": obj.get("locale") if obj.get("locale") is not None else 'en',
            "sales": [ProductInsightsRequestSalesInner.from_dict(_item) for _item in obj["sales"]] if obj.get("sales") is not None else None,
            "purchases": [ProductInsightsRequestPurchasesInner.from_dict(_item) for _item in obj["purchases"]] if obj.get("purchases") is not None else None,
            "cost_history": [ProductInsightsRequestCostHistoryInner.from_dict(_item) for _item in obj["cost_history"]] if obj.get("cost_history") is not None else None,
            "insight_settings": ProductInsightsRequestInsightSettings.from_dict(obj["insight_settings"]) if obj.get("insight_settings") is not None else None
        })
        return _obj


