# coding: utf-8

"""
    ForecastAPI

    Time series forecasting service with multiple algorithms and automatic method selection

    The version of the OpenAPI document: 2.0.2
    Contact: support@forecastapi.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import date
from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class ProductInsightsRequestPurchasesInner(BaseModel):
    """
    ProductInsightsRequestPurchasesInner
    """ # noqa: E501
    var_date: StrictStr = Field(alias="date")
    quantity_purchased: Union[Annotated[float, Field(strict=True, ge=0)], Annotated[int, Field(strict=True, ge=0)]]
    cost_price: Union[Annotated[float, Field(strict=True, ge=0)], Annotated[int, Field(strict=True, ge=0)]]
    cost_price_converted: Optional[Union[Annotated[float, Field(strict=True, ge=0)], Annotated[int, Field(strict=True, ge=0)]]] = None
    currency: Optional[Annotated[str, Field(min_length=3, strict=True, max_length=3)]] = None
    supplier_id: Optional[Annotated[str, Field(strict=True, max_length=255)]] = None
    purchase_order_date: Optional[date] = Field(default=None, description="Used for lead-time reliability analysis")
    expected_delivery_date: Optional[date] = None
    actual_delivery_date: Optional[date] = None
    __properties: ClassVar[List[str]] = ["date", "quantity_purchased", "cost_price", "cost_price_converted", "currency", "supplier_id", "purchase_order_date", "expected_delivery_date", "actual_delivery_date"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ProductInsightsRequestPurchasesInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if currency (nullable) is None
        # and model_fields_set contains the field
        if self.currency is None and "currency" in self.model_fields_set:
            _dict['currency'] = None

        # set to None if supplier_id (nullable) is None
        # and model_fields_set contains the field
        if self.supplier_id is None and "supplier_id" in self.model_fields_set:
            _dict['supplier_id'] = None

        # set to None if purchase_order_date (nullable) is None
        # and model_fields_set contains the field
        if self.purchase_order_date is None and "purchase_order_date" in self.model_fields_set:
            _dict['purchase_order_date'] = None

        # set to None if expected_delivery_date (nullable) is None
        # and model_fields_set contains the field
        if self.expected_delivery_date is None and "expected_delivery_date" in self.model_fields_set:
            _dict['expected_delivery_date'] = None

        # set to None if actual_delivery_date (nullable) is None
        # and model_fields_set contains the field
        if self.actual_delivery_date is None and "actual_delivery_date" in self.model_fields_set:
            _dict['actual_delivery_date'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ProductInsightsRequestPurchasesInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "date": obj.get("date"),
            "quantity_purchased": obj.get("quantity_purchased"),
            "cost_price": obj.get("cost_price"),
            "cost_price_converted": obj.get("cost_price_converted"),
            "currency": obj.get("currency"),
            "supplier_id": obj.get("supplier_id"),
            "purchase_order_date": obj.get("purchase_order_date"),
            "expected_delivery_date": obj.get("expected_delivery_date"),
            "actual_delivery_date": obj.get("actual_delivery_date")
        })
        return _obj


