# coding: utf-8

"""
    ForecastAPI

    Time series forecasting service with multiple algorithms and automatic method selection

    The version of the OpenAPI document: 2.0.3
    Contact: support@forecastapi.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class ProductInsightsRequestSalesInner(BaseModel):
    """
    ProductInsightsRequestSalesInner
    """ # noqa: E501
    var_date: StrictStr = Field(alias="date")
    quantity_sold: Union[Annotated[float, Field(strict=True, ge=0)], Annotated[int, Field(strict=True, ge=0)]]
    selling_price: Union[Annotated[float, Field(strict=True, ge=0)], Annotated[int, Field(strict=True, ge=0)]]
    selling_price_converted: Optional[Union[Annotated[float, Field(strict=True, ge=0)], Annotated[int, Field(strict=True, ge=0)]]] = Field(default=None, description="Price converted to base_currency, when the sale was in another currency")
    currency: Optional[Annotated[str, Field(min_length=3, strict=True, max_length=3)]] = None
    customer_id: Optional[Annotated[str, Field(strict=True, max_length=255)]] = None
    customer_segment: Optional[Annotated[str, Field(strict=True, max_length=255)]] = None
    __properties: ClassVar[List[str]] = ["date", "quantity_sold", "selling_price", "selling_price_converted", "currency", "customer_id", "customer_segment"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ProductInsightsRequestSalesInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if currency (nullable) is None
        # and model_fields_set contains the field
        if self.currency is None and "currency" in self.model_fields_set:
            _dict['currency'] = None

        # set to None if customer_id (nullable) is None
        # and model_fields_set contains the field
        if self.customer_id is None and "customer_id" in self.model_fields_set:
            _dict['customer_id'] = None

        # set to None if customer_segment (nullable) is None
        # and model_fields_set contains the field
        if self.customer_segment is None and "customer_segment" in self.model_fields_set:
            _dict['customer_segment'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ProductInsightsRequestSalesInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "date": obj.get("date"),
            "quantity_sold": obj.get("quantity_sold"),
            "selling_price": obj.get("selling_price"),
            "selling_price_converted": obj.get("selling_price_converted"),
            "currency": obj.get("currency"),
            "customer_id": obj.get("customer_id"),
            "customer_segment": obj.get("customer_segment")
        })
        return _obj


