# coding: utf-8

"""
    ForecastAPI

    Time series forecasting service with multiple algorithms and automatic method selection

    The version of the OpenAPI document: 2.0.4
    Contact: support@forecastapi.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from forecastapi.models.traffic_forecasting_request_data_inner import TrafficForecastingRequestDataInner
from forecastapi.models.traffic_forecasting_request_traffic_settings import TrafficForecastingRequestTrafficSettings
from typing import Optional, Set
from typing_extensions import Self

class TrafficForecastingRequest(BaseModel):
    """
    TrafficForecastingRequest
    """ # noqa: E501
    identifier: StrictStr = Field(description="Metric identifier (e.g., endpoint name, service name)")
    frequency: StrictStr = Field(description="Data frequency for forecasting: - M: Minute (for real-time traffic) - H: Hourly - D: Daily - W: Weekly - MS: Monthly (start of month) - ME: Monthly (end of month) - Q: Quarterly - Y: Yearly ")
    start_date: Optional[datetime] = Field(default=None, description="Optional start date for the forecast period")
    periods: Annotated[int, Field(strict=True, ge=1)] = Field(description="Number of periods to forecast ahead")
    enable_intelligent_aggregation: Optional[StrictBool] = Field(default=None, description="Enable intelligent data aggregation for improved forecasting")
    confidence_level: Optional[Union[Annotated[float, Field(le=0.99, strict=True, ge=0.1)], Annotated[int, Field(le=0, strict=True, ge=1)]]] = Field(default=None, description="Confidence level for forecast intervals (default 0.95)")
    data: Annotated[List[TrafficForecastingRequestDataInner], Field(min_length=1)] = Field(description="Historical traffic data for forecasting")
    traffic_settings: TrafficForecastingRequestTrafficSettings
    __properties: ClassVar[List[str]] = ["identifier", "frequency", "start_date", "periods", "enable_intelligent_aggregation", "confidence_level", "data", "traffic_settings"]

    @field_validator('frequency')
    def frequency_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['M', 'H', 'D', 'W', 'MS', 'ME', 'Q', 'Y']):
            raise ValueError("must be one of enum values ('M', 'H', 'D', 'W', 'MS', 'ME', 'Q', 'Y')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TrafficForecastingRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in data (list)
        _items = []
        if self.data:
            for _item_data in self.data:
                if _item_data:
                    _items.append(_item_data.to_dict())
            _dict['data'] = _items
        # override the default output from pydantic by calling `to_dict()` of traffic_settings
        if self.traffic_settings:
            _dict['traffic_settings'] = self.traffic_settings.to_dict()
        # set to None if start_date (nullable) is None
        # and model_fields_set contains the field
        if self.start_date is None and "start_date" in self.model_fields_set:
            _dict['start_date'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TrafficForecastingRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "identifier": obj.get("identifier"),
            "frequency": obj.get("frequency"),
            "start_date": obj.get("start_date"),
            "periods": obj.get("periods"),
            "enable_intelligent_aggregation": obj.get("enable_intelligent_aggregation"),
            "confidence_level": obj.get("confidence_level"),
            "data": [TrafficForecastingRequestDataInner.from_dict(_item) for _item in obj["data"]] if obj.get("data") is not None else None,
            "traffic_settings": TrafficForecastingRequestTrafficSettings.from_dict(obj["traffic_settings"]) if obj.get("traffic_settings") is not None else None
        })
        return _obj


