# coding: utf-8

"""
    ForecastAPI

    Time series forecasting service with multiple algorithms and automatic method selection

    The version of the OpenAPI document: 2.0.4
    Contact: support@forecastapi.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class TrafficForecastingRequestTrafficSettings(BaseModel):
    """
    Infrastructure and traffic configuration
    """ # noqa: E501
    current_capacity: Union[Annotated[float, Field(strict=True, ge=1)], Annotated[int, Field(strict=True, ge=1)]] = Field(description="Current infrastructure capacity (requests, users, etc.)")
    baseline_traffic: Union[Annotated[float, Field(strict=True, ge=0)], Annotated[int, Field(strict=True, ge=0)]] = Field(description="Normal/expected traffic level for comparison")
    scaling_buffer: Optional[Union[Annotated[float, Field(le=1, strict=True, ge=0)], Annotated[int, Field(le=1, strict=True, ge=0)]]] = Field(default=None, description="Buffer percentage for scaling decisions (default 0.2 = 20%)")
    scale_up_threshold: Optional[Union[Annotated[float, Field(le=1, strict=True, ge=0)], Annotated[int, Field(le=1, strict=True, ge=0)]]] = Field(default=None, description="Utilization threshold to trigger scale up (default 0.8 = 80%)")
    scale_down_threshold: Optional[Union[Annotated[float, Field(le=1, strict=True, ge=0)], Annotated[int, Field(le=1, strict=True, ge=0)]]] = Field(default=None, description="Utilization threshold to trigger scale down (default 0.3 = 30%)")
    alert_threshold: Optional[Union[Annotated[float, Field(strict=True, ge=1)], Annotated[int, Field(strict=True, ge=1)]]] = Field(default=None, description="Traffic spike alert threshold as multiplier of baseline (default 1.5 = 150%)")
    anomaly_threshold: Optional[Union[Annotated[float, Field(strict=True, ge=1)], Annotated[int, Field(strict=True, ge=1)]]] = Field(default=None, description="Standard deviations for anomaly detection (default 3.0)")
    cost_per_unit: Optional[Union[Annotated[float, Field(strict=True, ge=0)], Annotated[int, Field(strict=True, ge=0)]]] = Field(default=None, description="Variable cost per traffic unit (default 0.01)")
    fixed_cost_per_capacity: Optional[Union[Annotated[float, Field(strict=True, ge=0)], Annotated[int, Field(strict=True, ge=0)]]] = Field(default=None, description="Fixed cost per capacity unit (default 0.1)")
    base_scaling_time: Optional[Annotated[int, Field(strict=True, ge=1)]] = Field(default=None, description="Base time in minutes for scaling operations (default 5)")
    enable_auto_scaling: Optional[StrictBool] = Field(default=None, description="Whether auto-scaling is currently enabled (default false)")
    __properties: ClassVar[List[str]] = ["current_capacity", "baseline_traffic", "scaling_buffer", "scale_up_threshold", "scale_down_threshold", "alert_threshold", "anomaly_threshold", "cost_per_unit", "fixed_cost_per_capacity", "base_scaling_time", "enable_auto_scaling"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TrafficForecastingRequestTrafficSettings from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if scaling_buffer (nullable) is None
        # and model_fields_set contains the field
        if self.scaling_buffer is None and "scaling_buffer" in self.model_fields_set:
            _dict['scaling_buffer'] = None

        # set to None if scale_up_threshold (nullable) is None
        # and model_fields_set contains the field
        if self.scale_up_threshold is None and "scale_up_threshold" in self.model_fields_set:
            _dict['scale_up_threshold'] = None

        # set to None if scale_down_threshold (nullable) is None
        # and model_fields_set contains the field
        if self.scale_down_threshold is None and "scale_down_threshold" in self.model_fields_set:
            _dict['scale_down_threshold'] = None

        # set to None if alert_threshold (nullable) is None
        # and model_fields_set contains the field
        if self.alert_threshold is None and "alert_threshold" in self.model_fields_set:
            _dict['alert_threshold'] = None

        # set to None if anomaly_threshold (nullable) is None
        # and model_fields_set contains the field
        if self.anomaly_threshold is None and "anomaly_threshold" in self.model_fields_set:
            _dict['anomaly_threshold'] = None

        # set to None if cost_per_unit (nullable) is None
        # and model_fields_set contains the field
        if self.cost_per_unit is None and "cost_per_unit" in self.model_fields_set:
            _dict['cost_per_unit'] = None

        # set to None if fixed_cost_per_capacity (nullable) is None
        # and model_fields_set contains the field
        if self.fixed_cost_per_capacity is None and "fixed_cost_per_capacity" in self.model_fields_set:
            _dict['fixed_cost_per_capacity'] = None

        # set to None if base_scaling_time (nullable) is None
        # and model_fields_set contains the field
        if self.base_scaling_time is None and "base_scaling_time" in self.model_fields_set:
            _dict['base_scaling_time'] = None

        # set to None if enable_auto_scaling (nullable) is None
        # and model_fields_set contains the field
        if self.enable_auto_scaling is None and "enable_auto_scaling" in self.model_fields_set:
            _dict['enable_auto_scaling'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TrafficForecastingRequestTrafficSettings from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "current_capacity": obj.get("current_capacity"),
            "baseline_traffic": obj.get("baseline_traffic"),
            "scaling_buffer": obj.get("scaling_buffer"),
            "scale_up_threshold": obj.get("scale_up_threshold"),
            "scale_down_threshold": obj.get("scale_down_threshold"),
            "alert_threshold": obj.get("alert_threshold"),
            "anomaly_threshold": obj.get("anomaly_threshold"),
            "cost_per_unit": obj.get("cost_per_unit"),
            "fixed_cost_per_capacity": obj.get("fixed_cost_per_capacity"),
            "base_scaling_time": obj.get("base_scaling_time"),
            "enable_auto_scaling": obj.get("enable_auto_scaling")
        })
        return _obj


