# coding: utf-8

# flake8: noqa

"""
    ForecastAPI

    Time series forecasting service with multiple algorithms and automatic method selection

    The version of the OpenAPI document: 2.0.3
    Contact: support@forecastapi.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "AnalysisApi",
    "AnomalyDetectionApi",
    "BatchForecastingApi",
    "ForecastingApi",
    "GroupedForecastingApi",
    "HealthApi",
    "InventoryPlanningApi",
    "ProductInsightsApi",
    "TrafficForecastingApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "AccumulateOptions",
    "AccumulatedForecast",
    "AccumulatedForecastAssumptions",
    "AccumulatedForecastByPeriodInner",
    "AdjustedForecast",
    "AdjustedForecastAdjustmentsAppliedInner",
    "AdjustmentsInner",
    "AnalysisResponse",
    "AnalysisResponseMeta",
    "AnalysisResponseMetaTiming",
    "AnalysisResponseResult",
    "AnalysisResponseResultCharacteristics",
    "AnomalyDetectionRequest",
    "AnomalyDetectionRequestAllOfAnomalySettings",
    "AnomalyDetectionResponse",
    "AnomalyDetectionResponseMeta",
    "AnomalyDetectionResponseMetaTiming",
    "AnomalyDetectionResponseResult",
    "AnomalyDetectionResponseResultAnalysis",
    "AnomalyDetectionResponseResultAnalysisDetectionSummary",
    "AnomalyDetectionResponseResultAnomaliesInner",
    "BatchForecastAccepted",
    "BatchForecastRequest",
    "BatchForecastSeries",
    "BatchForecastSeriesDataInner",
    "BatchForecastStatusResponse",
    "BatchForecastStatusResponsePartsInner",
    "BatchForecastStatusResponseResults",
    "BatchForecastStatusResponseResultsSummary",
    "BatchPresignResponse",
    "BatchSeriesResult",
    "CreateBatchProductInsights422Response",
    "CreateBatchProductInsights500Response",
    "CreateForecast400Response",
    "CreateForecast502Response",
    "CreateInventoryPlan400Response",
    "CreateInventoryPlan500Response",
    "CreateProductInsights400Response",
    "CreateTrafficForecast500Response",
    "DetectAnomalies422Response",
    "DetectAnomalies422ResponseOneOf",
    "DetectAnomalies500Response",
    "ErrorResponse",
    "ForecastPeriod",
    "ForecastRequest",
    "ForecastRequestDataInner",
    "ForecastResponse",
    "ForecastResponseMeta",
    "ForecastResponseMetaTiming",
    "ForecastResponseResult",
    "GetApiRoot200Response",
    "GetGroupedForecast404Response",
    "GroupedForecastAccepted",
    "GroupedForecastNode",
    "GroupedForecastRequest",
    "GroupedForecastResults",
    "GroupedForecastResultsReconciliation",
    "GroupedForecastSeries",
    "GroupedForecastSeriesDataInner",
    "GroupedForecastStatusResponse",
    "HealthCheck200Response",
    "InventoryPlanningRequest",
    "InventoryPlanningRequestDataInner",
    "InventoryPlanningRequestInventorySettings",
    "InventoryPlanningRequestInventorySettingsSuppliersInner",
    "InventoryPlanningResponse",
    "InventoryPlanningResponseMeta",
    "InventoryPlanningResponseMetaTiming",
    "InventoryPlanningResponseResult",
    "InventoryPlanningResponseResultForecastDataInner",
    "InventoryPlanningResponseResultStockAnalysis",
    "InventoryPlanningResponseResultSuppliersInner",
    "ProductInsight",
    "ProductInsightRecommendation",
    "ProductInsightsBatchRequest",
    "ProductInsightsBatchStatusResponse",
    "ProductInsightsRequest",
    "ProductInsightsRequestBaselinePeriodDays",
    "ProductInsightsRequestCostHistoryInner",
    "ProductInsightsRequestInsightSettings",
    "ProductInsightsRequestPurchasesInner",
    "ProductInsightsRequestSalesInner",
    "ProductInsightsResponse",
    "ProductInsightsResponseMeta",
    "ProductInsightsResponseMetaDataQuality",
    "ProductInsightsResponseMetaTiming",
    "ProductInsightsResponseResult",
    "ProductInsightsResponseResultComparison",
    "ProductInsightsResponseResultComparisonDevelopments",
    "ProductInsightsResponseResultProductInfo",
    "ProductInsightsResponseResultSummary",
    "ProductInsightsResponseResultSummaryAnalysisPeriod",
    "TrafficForecastingRequest",
    "TrafficForecastingRequestDataInner",
    "TrafficForecastingRequestTrafficSettings",
    "TrafficForecastingResponse",
    "TrafficForecastingResponseMeta",
    "TrafficForecastingResponseMetaTiming",
    "TrafficForecastingResponseResult",
    "TrafficForecastingResponseResultCapacityAnalysis",
    "TrafficForecastingResponseResultCapacityAnalysisUtilizationPeriodsInner",
    "TrafficForecastingResponseResultCostOptimization",
    "TrafficForecastingResponseResultCostOptimizationCostBreakdown",
    "TrafficForecastingResponseResultCostOptimizationRecommendationsInner",
    "TrafficForecastingResponseResultForecastDataInner",
    "TrafficForecastingResponseResultScalingRecommendations",
    "TrafficForecastingResponseResultScalingRecommendationsRecommendationsInner",
    "TrafficForecastingResponseResultTrafficAlerts",
    "TrafficForecastingResponseResultTrafficAlertsAlertsInner",
    "ValidationErrorResponse",
    "ValidationFailedResponse",
    "ValueBounds",
]

# import apis into sdk package
from forecastapi.api.analysis_api import AnalysisApi as AnalysisApi
from forecastapi.api.anomaly_detection_api import AnomalyDetectionApi as AnomalyDetectionApi
from forecastapi.api.batch_forecasting_api import BatchForecastingApi as BatchForecastingApi
from forecastapi.api.forecasting_api import ForecastingApi as ForecastingApi
from forecastapi.api.grouped_forecasting_api import GroupedForecastingApi as GroupedForecastingApi
from forecastapi.api.health_api import HealthApi as HealthApi
from forecastapi.api.inventory_planning_api import InventoryPlanningApi as InventoryPlanningApi
from forecastapi.api.product_insights_api import ProductInsightsApi as ProductInsightsApi
from forecastapi.api.traffic_forecasting_api import TrafficForecastingApi as TrafficForecastingApi

# import ApiClient
from forecastapi.api_response import ApiResponse as ApiResponse
from forecastapi.api_client import ApiClient as ApiClient
from forecastapi.configuration import Configuration as Configuration
from forecastapi.exceptions import OpenApiException as OpenApiException
from forecastapi.exceptions import ApiTypeError as ApiTypeError
from forecastapi.exceptions import ApiValueError as ApiValueError
from forecastapi.exceptions import ApiKeyError as ApiKeyError
from forecastapi.exceptions import ApiAttributeError as ApiAttributeError
from forecastapi.exceptions import ApiException as ApiException

# import models into sdk package
from forecastapi.models.accumulate_options import AccumulateOptions as AccumulateOptions
from forecastapi.models.accumulated_forecast import AccumulatedForecast as AccumulatedForecast
from forecastapi.models.accumulated_forecast_assumptions import AccumulatedForecastAssumptions as AccumulatedForecastAssumptions
from forecastapi.models.accumulated_forecast_by_period_inner import AccumulatedForecastByPeriodInner as AccumulatedForecastByPeriodInner
from forecastapi.models.adjusted_forecast import AdjustedForecast as AdjustedForecast
from forecastapi.models.adjusted_forecast_adjustments_applied_inner import AdjustedForecastAdjustmentsAppliedInner as AdjustedForecastAdjustmentsAppliedInner
from forecastapi.models.adjustments_inner import AdjustmentsInner as AdjustmentsInner
from forecastapi.models.analysis_response import AnalysisResponse as AnalysisResponse
from forecastapi.models.analysis_response_meta import AnalysisResponseMeta as AnalysisResponseMeta
from forecastapi.models.analysis_response_meta_timing import AnalysisResponseMetaTiming as AnalysisResponseMetaTiming
from forecastapi.models.analysis_response_result import AnalysisResponseResult as AnalysisResponseResult
from forecastapi.models.analysis_response_result_characteristics import AnalysisResponseResultCharacteristics as AnalysisResponseResultCharacteristics
from forecastapi.models.anomaly_detection_request import AnomalyDetectionRequest as AnomalyDetectionRequest
from forecastapi.models.anomaly_detection_request_all_of_anomaly_settings import AnomalyDetectionRequestAllOfAnomalySettings as AnomalyDetectionRequestAllOfAnomalySettings
from forecastapi.models.anomaly_detection_response import AnomalyDetectionResponse as AnomalyDetectionResponse
from forecastapi.models.anomaly_detection_response_meta import AnomalyDetectionResponseMeta as AnomalyDetectionResponseMeta
from forecastapi.models.anomaly_detection_response_meta_timing import AnomalyDetectionResponseMetaTiming as AnomalyDetectionResponseMetaTiming
from forecastapi.models.anomaly_detection_response_result import AnomalyDetectionResponseResult as AnomalyDetectionResponseResult
from forecastapi.models.anomaly_detection_response_result_analysis import AnomalyDetectionResponseResultAnalysis as AnomalyDetectionResponseResultAnalysis
from forecastapi.models.anomaly_detection_response_result_analysis_detection_summary import AnomalyDetectionResponseResultAnalysisDetectionSummary as AnomalyDetectionResponseResultAnalysisDetectionSummary
from forecastapi.models.anomaly_detection_response_result_anomalies_inner import AnomalyDetectionResponseResultAnomaliesInner as AnomalyDetectionResponseResultAnomaliesInner
from forecastapi.models.batch_forecast_accepted import BatchForecastAccepted as BatchForecastAccepted
from forecastapi.models.batch_forecast_request import BatchForecastRequest as BatchForecastRequest
from forecastapi.models.batch_forecast_series import BatchForecastSeries as BatchForecastSeries
from forecastapi.models.batch_forecast_series_data_inner import BatchForecastSeriesDataInner as BatchForecastSeriesDataInner
from forecastapi.models.batch_forecast_status_response import BatchForecastStatusResponse as BatchForecastStatusResponse
from forecastapi.models.batch_forecast_status_response_parts_inner import BatchForecastStatusResponsePartsInner as BatchForecastStatusResponsePartsInner
from forecastapi.models.batch_forecast_status_response_results import BatchForecastStatusResponseResults as BatchForecastStatusResponseResults
from forecastapi.models.batch_forecast_status_response_results_summary import BatchForecastStatusResponseResultsSummary as BatchForecastStatusResponseResultsSummary
from forecastapi.models.batch_presign_response import BatchPresignResponse as BatchPresignResponse
from forecastapi.models.batch_series_result import BatchSeriesResult as BatchSeriesResult
from forecastapi.models.create_batch_product_insights422_response import CreateBatchProductInsights422Response as CreateBatchProductInsights422Response
from forecastapi.models.create_batch_product_insights500_response import CreateBatchProductInsights500Response as CreateBatchProductInsights500Response
from forecastapi.models.create_forecast400_response import CreateForecast400Response as CreateForecast400Response
from forecastapi.models.create_forecast502_response import CreateForecast502Response as CreateForecast502Response
from forecastapi.models.create_inventory_plan400_response import CreateInventoryPlan400Response as CreateInventoryPlan400Response
from forecastapi.models.create_inventory_plan500_response import CreateInventoryPlan500Response as CreateInventoryPlan500Response
from forecastapi.models.create_product_insights400_response import CreateProductInsights400Response as CreateProductInsights400Response
from forecastapi.models.create_traffic_forecast500_response import CreateTrafficForecast500Response as CreateTrafficForecast500Response
from forecastapi.models.detect_anomalies422_response import DetectAnomalies422Response as DetectAnomalies422Response
from forecastapi.models.detect_anomalies422_response_one_of import DetectAnomalies422ResponseOneOf as DetectAnomalies422ResponseOneOf
from forecastapi.models.detect_anomalies500_response import DetectAnomalies500Response as DetectAnomalies500Response
from forecastapi.models.error_response import ErrorResponse as ErrorResponse
from forecastapi.models.forecast_period import ForecastPeriod as ForecastPeriod
from forecastapi.models.forecast_request import ForecastRequest as ForecastRequest
from forecastapi.models.forecast_request_data_inner import ForecastRequestDataInner as ForecastRequestDataInner
from forecastapi.models.forecast_response import ForecastResponse as ForecastResponse
from forecastapi.models.forecast_response_meta import ForecastResponseMeta as ForecastResponseMeta
from forecastapi.models.forecast_response_meta_timing import ForecastResponseMetaTiming as ForecastResponseMetaTiming
from forecastapi.models.forecast_response_result import ForecastResponseResult as ForecastResponseResult
from forecastapi.models.get_api_root200_response import GetApiRoot200Response as GetApiRoot200Response
from forecastapi.models.get_grouped_forecast404_response import GetGroupedForecast404Response as GetGroupedForecast404Response
from forecastapi.models.grouped_forecast_accepted import GroupedForecastAccepted as GroupedForecastAccepted
from forecastapi.models.grouped_forecast_node import GroupedForecastNode as GroupedForecastNode
from forecastapi.models.grouped_forecast_request import GroupedForecastRequest as GroupedForecastRequest
from forecastapi.models.grouped_forecast_results import GroupedForecastResults as GroupedForecastResults
from forecastapi.models.grouped_forecast_results_reconciliation import GroupedForecastResultsReconciliation as GroupedForecastResultsReconciliation
from forecastapi.models.grouped_forecast_series import GroupedForecastSeries as GroupedForecastSeries
from forecastapi.models.grouped_forecast_series_data_inner import GroupedForecastSeriesDataInner as GroupedForecastSeriesDataInner
from forecastapi.models.grouped_forecast_status_response import GroupedForecastStatusResponse as GroupedForecastStatusResponse
from forecastapi.models.health_check200_response import HealthCheck200Response as HealthCheck200Response
from forecastapi.models.inventory_planning_request import InventoryPlanningRequest as InventoryPlanningRequest
from forecastapi.models.inventory_planning_request_data_inner import InventoryPlanningRequestDataInner as InventoryPlanningRequestDataInner
from forecastapi.models.inventory_planning_request_inventory_settings import InventoryPlanningRequestInventorySettings as InventoryPlanningRequestInventorySettings
from forecastapi.models.inventory_planning_request_inventory_settings_suppliers_inner import InventoryPlanningRequestInventorySettingsSuppliersInner as InventoryPlanningRequestInventorySettingsSuppliersInner
from forecastapi.models.inventory_planning_response import InventoryPlanningResponse as InventoryPlanningResponse
from forecastapi.models.inventory_planning_response_meta import InventoryPlanningResponseMeta as InventoryPlanningResponseMeta
from forecastapi.models.inventory_planning_response_meta_timing import InventoryPlanningResponseMetaTiming as InventoryPlanningResponseMetaTiming
from forecastapi.models.inventory_planning_response_result import InventoryPlanningResponseResult as InventoryPlanningResponseResult
from forecastapi.models.inventory_planning_response_result_forecast_data_inner import InventoryPlanningResponseResultForecastDataInner as InventoryPlanningResponseResultForecastDataInner
from forecastapi.models.inventory_planning_response_result_stock_analysis import InventoryPlanningResponseResultStockAnalysis as InventoryPlanningResponseResultStockAnalysis
from forecastapi.models.inventory_planning_response_result_suppliers_inner import InventoryPlanningResponseResultSuppliersInner as InventoryPlanningResponseResultSuppliersInner
from forecastapi.models.product_insight import ProductInsight as ProductInsight
from forecastapi.models.product_insight_recommendation import ProductInsightRecommendation as ProductInsightRecommendation
from forecastapi.models.product_insights_batch_request import ProductInsightsBatchRequest as ProductInsightsBatchRequest
from forecastapi.models.product_insights_batch_status_response import ProductInsightsBatchStatusResponse as ProductInsightsBatchStatusResponse
from forecastapi.models.product_insights_request import ProductInsightsRequest as ProductInsightsRequest
from forecastapi.models.product_insights_request_baseline_period_days import ProductInsightsRequestBaselinePeriodDays as ProductInsightsRequestBaselinePeriodDays
from forecastapi.models.product_insights_request_cost_history_inner import ProductInsightsRequestCostHistoryInner as ProductInsightsRequestCostHistoryInner
from forecastapi.models.product_insights_request_insight_settings import ProductInsightsRequestInsightSettings as ProductInsightsRequestInsightSettings
from forecastapi.models.product_insights_request_purchases_inner import ProductInsightsRequestPurchasesInner as ProductInsightsRequestPurchasesInner
from forecastapi.models.product_insights_request_sales_inner import ProductInsightsRequestSalesInner as ProductInsightsRequestSalesInner
from forecastapi.models.product_insights_response import ProductInsightsResponse as ProductInsightsResponse
from forecastapi.models.product_insights_response_meta import ProductInsightsResponseMeta as ProductInsightsResponseMeta
from forecastapi.models.product_insights_response_meta_data_quality import ProductInsightsResponseMetaDataQuality as ProductInsightsResponseMetaDataQuality
from forecastapi.models.product_insights_response_meta_timing import ProductInsightsResponseMetaTiming as ProductInsightsResponseMetaTiming
from forecastapi.models.product_insights_response_result import ProductInsightsResponseResult as ProductInsightsResponseResult
from forecastapi.models.product_insights_response_result_comparison import ProductInsightsResponseResultComparison as ProductInsightsResponseResultComparison
from forecastapi.models.product_insights_response_result_comparison_developments import ProductInsightsResponseResultComparisonDevelopments as ProductInsightsResponseResultComparisonDevelopments
from forecastapi.models.product_insights_response_result_product_info import ProductInsightsResponseResultProductInfo as ProductInsightsResponseResultProductInfo
from forecastapi.models.product_insights_response_result_summary import ProductInsightsResponseResultSummary as ProductInsightsResponseResultSummary
from forecastapi.models.product_insights_response_result_summary_analysis_period import ProductInsightsResponseResultSummaryAnalysisPeriod as ProductInsightsResponseResultSummaryAnalysisPeriod
from forecastapi.models.traffic_forecasting_request import TrafficForecastingRequest as TrafficForecastingRequest
from forecastapi.models.traffic_forecasting_request_data_inner import TrafficForecastingRequestDataInner as TrafficForecastingRequestDataInner
from forecastapi.models.traffic_forecasting_request_traffic_settings import TrafficForecastingRequestTrafficSettings as TrafficForecastingRequestTrafficSettings
from forecastapi.models.traffic_forecasting_response import TrafficForecastingResponse as TrafficForecastingResponse
from forecastapi.models.traffic_forecasting_response_meta import TrafficForecastingResponseMeta as TrafficForecastingResponseMeta
from forecastapi.models.traffic_forecasting_response_meta_timing import TrafficForecastingResponseMetaTiming as TrafficForecastingResponseMetaTiming
from forecastapi.models.traffic_forecasting_response_result import TrafficForecastingResponseResult as TrafficForecastingResponseResult
from forecastapi.models.traffic_forecasting_response_result_capacity_analysis import TrafficForecastingResponseResultCapacityAnalysis as TrafficForecastingResponseResultCapacityAnalysis
from forecastapi.models.traffic_forecasting_response_result_capacity_analysis_utilization_periods_inner import TrafficForecastingResponseResultCapacityAnalysisUtilizationPeriodsInner as TrafficForecastingResponseResultCapacityAnalysisUtilizationPeriodsInner
from forecastapi.models.traffic_forecasting_response_result_cost_optimization import TrafficForecastingResponseResultCostOptimization as TrafficForecastingResponseResultCostOptimization
from forecastapi.models.traffic_forecasting_response_result_cost_optimization_cost_breakdown import TrafficForecastingResponseResultCostOptimizationCostBreakdown as TrafficForecastingResponseResultCostOptimizationCostBreakdown
from forecastapi.models.traffic_forecasting_response_result_cost_optimization_recommendations_inner import TrafficForecastingResponseResultCostOptimizationRecommendationsInner as TrafficForecastingResponseResultCostOptimizationRecommendationsInner
from forecastapi.models.traffic_forecasting_response_result_forecast_data_inner import TrafficForecastingResponseResultForecastDataInner as TrafficForecastingResponseResultForecastDataInner
from forecastapi.models.traffic_forecasting_response_result_scaling_recommendations import TrafficForecastingResponseResultScalingRecommendations as TrafficForecastingResponseResultScalingRecommendations
from forecastapi.models.traffic_forecasting_response_result_scaling_recommendations_recommendations_inner import TrafficForecastingResponseResultScalingRecommendationsRecommendationsInner as TrafficForecastingResponseResultScalingRecommendationsRecommendationsInner
from forecastapi.models.traffic_forecasting_response_result_traffic_alerts import TrafficForecastingResponseResultTrafficAlerts as TrafficForecastingResponseResultTrafficAlerts
from forecastapi.models.traffic_forecasting_response_result_traffic_alerts_alerts_inner import TrafficForecastingResponseResultTrafficAlertsAlertsInner as TrafficForecastingResponseResultTrafficAlertsAlertsInner
from forecastapi.models.validation_error_response import ValidationErrorResponse as ValidationErrorResponse
from forecastapi.models.validation_failed_response import ValidationFailedResponse as ValidationFailedResponse
from forecastapi.models.value_bounds import ValueBounds as ValueBounds

